export default {
  'ec.menu.name.software': '软件资源',
  'ec.menu.name.softwareAssets': '软件台账',

  'ec.software.common.code': '软件编码',
  'ec.software.common.name': '软件名称',
  'ec.software.common.systemType': '软件类型',
  'ec.software.common.versionNo': '版本号',
  'ec.software.common.deploymentArchitecture': '部署架构',
  'ec.software.common.owner': '负责人',
  'ec.software.common.contactPhone': '联系电话',
  'ec.software.common.status': '状态',
  'ec.software.common.remark': '备注',
  'ec.software.common.createdAt': '创建时间',
  'ec.software.common.updatedAt': '更新时间',
  'ec.software.common.actions': '操作',
  'ec.software.common.search': '关键字',
  'ec.software.common.searchPlaceholder': '请输入软件编码或名称',
  'ec.software.common.create': '新增软件',
  'ec.software.common.edit': '编辑',
  'ec.software.common.detail': '详情',
  'ec.software.common.relations': '关联维护',
  'ec.software.common.delete': '删除',
  'ec.software.common.empty': '暂无软件数据',
  'ec.software.common.noData': '暂无数据',
  'ec.software.common.noRelation': '暂无关联数据',
  'ec.software.common.saveSuccess': '软件保存成功',
  'ec.software.common.saveFailed': '软件保存失败',
  'ec.software.common.deleteSuccess': '软件删除成功',
  'ec.software.common.deleteFailed': '软件删除失败',
  'ec.software.common.deleteConfirm': '确定删除“{name}”吗？',

  'ec.software.section.basic': '基本信息',
  'ec.software.section.relations': '关联信息',

  'ec.software.page.createTitle': '新增软件',
  'ec.software.page.createDescription': '按新版正式入口录入软件基础信息，并同步维护关联人员、服务商和硬件。',
  'ec.software.page.editTitle': '编辑软件',
  'ec.software.page.editDescription': '调整软件基础信息和关联对象，保持新版正式入口交互一致。',
  'ec.software.page.detailTitle': '软件详情',
  'ec.software.page.detailDescription': '查看软件基础信息，以及关联人员、服务商、硬件和项目。',
  'ec.software.page.relationsTitle': '软件关联维护',
  'ec.software.page.relationsDescription': '集中维护当前软件关联的人员、服务商和硬件。',

  'ec.software.type.externalService': '对外服务',
  'ec.software.type.internalOffice': '内部办公',
  'ec.software.type.databaseSoftware': '数据库软件',
  'ec.software.type.basicSupport': '基础支撑',
  'ec.software.type.securitySoftware': '安全软件',
  'ec.software.type.supportSystem': '支撑系统',

  'ec.software.deployment.single': '单机',
  'ec.software.deployment.cluster': '集群',
  'ec.software.deployment.containerized': '容器化',

  'ec.software.stats.total': '软件总数',
  'ec.software.stats.externalService': '对外服务',
  'ec.software.stats.internalOffice': '内部办公',
  'ec.software.stats.databaseSoftware': '数据库软件',
  'ec.software.stats.basicSupport': '基础支撑',
  'ec.software.stats.securitySoftware': '安全软件',

  'ec.software.form.codePlaceholder': '请输入软件编码',
  'ec.software.form.namePlaceholder': '请输入软件名称',
  'ec.software.form.systemTypePlaceholder': '请选择软件类型',
  'ec.software.form.versionNoPlaceholder': '请输入版本号',
  'ec.software.form.deploymentArchitecturePlaceholder': '请选择部署架构',
  'ec.software.form.ownerPlaceholder': '请输入负责人',
  'ec.software.form.ownerSelectTitle': '选择负责人',
  'ec.software.form.contactPhonePlaceholder': '请输入联系电话',
  'ec.software.form.statusPlaceholder': '请选择软件状态',
  'ec.software.form.remarkPlaceholder': '请输入备注',
  'ec.software.form.createTitle': '新增软件',
  'ec.software.form.editTitle': '编辑软件',

  'ec.software.validation.codeRequired': '请输入软件编码',
  'ec.software.validation.nameRequired': '请输入软件名称',
  'ec.software.validation.systemTypeRequired': '请选择软件类型',
  'ec.software.validation.versionNoRequired': '请输入版本号',
  'ec.software.validation.deploymentArchitectureRequired': '请选择部署架构',
  'ec.software.validation.ownerRequired': '请输入负责人',
  'ec.software.validation.contactPhoneRequired': '请输入联系电话',
  'ec.software.validation.statusRequired': '请选择软件状态',

  'ec.software.detail.title': '软件详情',
  'ec.software.detail.basic': '基础信息',
  'ec.software.detail.serviceProviders': '关联服务商',
  'ec.software.detail.persons': '关联人员',
  'ec.software.detail.hardwareAssets': '关联硬件',
  'ec.software.detail.projects': '关联项目',

  'ec.software.card.creditCode': '统一社会信用代码',
  'ec.software.card.contact': '商务联系人',
  'ec.software.card.phone': '联系电话',
  'ec.software.card.employeeNo': '工号',
  'ec.software.card.mobile': '手机号',
  'ec.software.card.assetCode': '资产编码',
  'ec.software.card.managementIp': '管理 IP',
  'ec.software.card.cpuModel': 'CPU 型号',
  'ec.software.card.memoryGb': '内存(GB)',
  'ec.software.card.projectType': '项目类型',
  'ec.software.card.projectStatus': '项目状态',
  'ec.software.card.ownerName': '负责人',
  'ec.software.card.approvalBatchNo': '批复文号',

  'ec.software.relation.title': '同步软件关联关系',
  'ec.software.relation.serviceProvidersPlaceholder': '请选择服务商',
  'ec.software.relation.personsPlaceholder': '请选择人员',
  'ec.software.relation.projectsPlaceholder': '请选择项目',
  'ec.software.relation.hardwareAssetsPlaceholder': '请选择硬件',
  'ec.software.relation.saveSuccess': '软件关系同步成功',
  'ec.software.relation.saveFailed': '软件关系同步失败',
  'ec.software.relation.partialSaveSuccess': '软件基础信息已保存，但关联关系同步失败，请进入关联维护页检查',

  'ec.software.message.loadFailed': '软件列表加载失败',
  'ec.software.message.detailFailed': '软件详情加载失败',
  'ec.software.message.supportLoadFailed': '软件支撑选项加载失败',
  'ec.software.message.statsFailed': '软件统计加载失败',
}
