export default {
  'ec.menu.name.software': '软件资源',
  'ec.menu.name.softwareAssets': '软件台账',

  'ec.software.common.code': '系统编码',
  'ec.software.common.name': '系统名称',
  'ec.software.common.systemType': '系统类型',
  'ec.software.common.status': '状态',
  'ec.software.common.remark': '备注',
  'ec.software.common.createdAt': '创建时间',
  'ec.software.common.updatedAt': '更新时间',
  'ec.software.common.actions': '操作',
  'ec.software.common.search': '关键字',
  'ec.software.common.searchPlaceholder': '请输入系统编码或名称',
  'ec.software.common.create': '新增软件',
  'ec.software.common.edit': '编辑',
  'ec.software.common.detail': '详情',
  'ec.software.common.relations': '关联维护',
  'ec.software.common.delete': '删除',
  'ec.software.common.empty': '暂无软件数据',
  'ec.software.common.noData': '暂无数据',
  'ec.software.common.saveSuccess': '软件保存成功',
  'ec.software.common.saveFailed': '软件保存失败',
  'ec.software.common.deleteSuccess': '软件删除成功',
  'ec.software.common.deleteFailed': '软件删除失败',
  'ec.software.common.deleteConfirm': '确定删除“{name}”吗？',

  'ec.software.type.externalService': '对外服务系统',
  'ec.software.type.internalOffice': '内部办公系统',
  'ec.software.type.supportSystem': '支撑系统',

  'ec.software.form.codePlaceholder': '请输入系统编码',
  'ec.software.form.namePlaceholder': '请输入系统名称',
  'ec.software.form.systemTypePlaceholder': '请选择系统类型',
  'ec.software.form.statusPlaceholder': '请选择系统状态',
  'ec.software.form.remarkPlaceholder': '请输入备注',
  'ec.software.form.createTitle': '新增软件',
  'ec.software.form.editTitle': '编辑软件',

  'ec.software.validation.codeRequired': '请输入系统编码',
  'ec.software.validation.nameRequired': '请输入系统名称',
  'ec.software.validation.systemTypeRequired': '请选择系统类型',
  'ec.software.validation.statusRequired': '请选择系统状态',

  'ec.software.detail.title': '软件详情',
  'ec.software.detail.basic': '基础信息',
  'ec.software.detail.serviceProviders': '服务商',
  'ec.software.detail.persons': '负责人',
  'ec.software.detail.projects': '关联项目',

  'ec.software.relation.title': '同步软件关联关系',
  'ec.software.relation.serviceProvidersPlaceholder': '请选择服务商',
  'ec.software.relation.personsPlaceholder': '请选择人员',
  'ec.software.relation.projectsPlaceholder': '请选择项目',
  'ec.software.relation.saveSuccess': '软件关系同步成功',
  'ec.software.relation.saveFailed': '软件关系同步失败',

  'ec.software.message.loadFailed': '软件列表加载失败',
  'ec.software.message.detailFailed': '软件详情加载失败',
  'ec.software.message.supportLoadFailed': '软件支撑选项加载失败',
}
