export default {
  'ec.monitor.dashboard.filter.keyword': 'Filter',
  'ec.monitor.dashboard.filter.keyword.placeholder': 'Search hostname, OS, or agent identifier',
  'ec.monitor.dashboard.filter.activeAgent': 'Active agent',
  'ec.monitor.dashboard.summary.total': 'Total agents',
  'ec.monitor.dashboard.summary.online': 'Online',
  'ec.monitor.dashboard.summary.offline': 'Offline',
  'ec.monitor.dashboard.summary.abnormal': 'Abnormal processes',
  'ec.monitor.dashboard.empty': 'No agents matched the current filter',
  'ec.monitor.dashboard.banner.title': 'Active alerts',
  'ec.monitor.dashboard.banner.ackAll': 'Acknowledge all',
  'ec.monitor.dashboard.banner.ackOne': 'Acknowledge',
  'ec.monitor.dashboard.card.online': 'Online',
  'ec.monitor.dashboard.card.offline': 'Offline',
  'ec.monitor.dashboard.card.cpu': 'CPU',
  'ec.monitor.dashboard.card.memory': 'Memory',
  'ec.monitor.dashboard.card.disk': 'Disk',
  'ec.monitor.dashboard.card.alerts': 'Alerts',
  'ec.monitor.dashboard.card.logs': 'Logs',
  'ec.monitor.dashboard.detail.title': 'Agent detail',
  'ec.monitor.dashboard.detail.summary': 'Summary',
  'ec.monitor.dashboard.detail.hardware': 'Hardware details',
  'ec.monitor.dashboard.detail.agentId': 'Agent ID',
  'ec.monitor.dashboard.detail.host': 'Hostname',
  'ec.monitor.dashboard.detail.status': 'Status',
  'ec.monitor.dashboard.detail.online': 'Online',
  'ec.monitor.dashboard.detail.offline': 'Offline',
  'ec.monitor.dashboard.detail.os': 'Operating system',
  'ec.monitor.dashboard.detail.cpu': 'CPU',
  'ec.monitor.dashboard.detail.memory': 'Memory',
  'ec.monitor.dashboard.detail.osArchitecture': 'Architecture',
  'ec.monitor.dashboard.detail.cpuCores': 'Logical cores',
  'ec.monitor.dashboard.detail.cpuModel': 'CPU model',
  'ec.monitor.dashboard.detail.memoryUsage': 'Memory usage',
  'ec.monitor.dashboard.detail.memorySpec': 'Memory spec',
  'ec.monitor.dashboard.detail.mainBoard': 'Mainboard',
  'ec.monitor.dashboard.detail.diskOverview': 'Disk overview',
  'ec.monitor.dashboard.detail.gpu': 'GPU',
  'ec.monitor.dashboard.detail.processCount': 'Process count',
  'ec.monitor.dashboard.detail.feedbackTime': 'Last report',
  'ec.monitor.dashboard.detail.available': 'Available',
  'ec.monitor.dashboard.detail.partitions': 'partitions',
  'ec.monitor.dashboard.detail.disks': 'Disk partitions',
  'ec.monitor.dashboard.detail.processes': 'Processes',
  'ec.monitor.dashboard.detail.recentLogs': 'Recent logs',
  'ec.monitor.dashboard.detail.noLogs': 'No realtime logs',
  'ec.monitor.dashboard.detail.actions': 'Quick actions',
  'ec.monitor.dashboard.detail.rules': 'Alert rules',
  'ec.monitor.dashboard.detail.viewAlerts': 'View alerts',
  'ec.monitor.dashboard.detail.viewLogs': 'View logs',
  'ec.monitor.dashboard.detail.logMonitors': 'Log monitors',
  'ec.monitor.dashboard.detail.filterRules': 'Filter rules',
  'ec.monitor.dashboard.detail.ttyd': 'TTYD',
  'ec.monitor.dashboard.detail.noProcesses': 'No process data',
  'ec.monitor.dashboard.process.running': 'Running',
  'ec.monitor.dashboard.process.stopped': 'Stopped',
  'ec.monitor.dashboard.alerts.title': 'System alerts - {agentId}',
  'ec.monitor.dashboard.alerts.empty': 'No pending alerts',
  'ec.monitor.dashboard.alerts.level.critical': 'Critical',
  'ec.monitor.dashboard.alerts.level.warning': 'Warning',
  'ec.monitor.dashboard.logs.title': 'Hit logs - {agentId}',
  'ec.monitor.dashboard.logs.empty': 'No matching logs',
  'ec.monitor.dashboard.rules.title': 'Alert rules - {agentId}',
  'ec.monitor.dashboard.rules.empty': 'No rules configured',
  'ec.monitor.dashboard.rules.create': 'Create rule',
  'ec.monitor.dashboard.rules.ruleName': 'Rule name',
  'ec.monitor.dashboard.rules.ruleName.placeholder': 'Example: High CPU and low memory',
  'ec.monitor.dashboard.rules.alertLevel': 'Alert level',
  'ec.monitor.dashboard.rules.cooldownSec': 'Cooldown (sec)',
  'ec.monitor.dashboard.rules.topLogic': 'Top logic',
  'ec.monitor.dashboard.rules.groupLogic': 'Group logic',
  'ec.monitor.dashboard.rules.addGroup': 'Add group',
  'ec.monitor.dashboard.rules.addCondition': 'Add condition',
  'ec.monitor.dashboard.rules.delete': 'Delete',
  'ec.monitor.dashboard.rules.save': 'Save rule',
  'ec.monitor.dashboard.rules.cancel': 'Cancel',
  'ec.monitor.dashboard.rules.enabled': 'Enabled',
  'ec.monitor.dashboard.rules.disabled': 'Disabled',
  'ec.monitor.dashboard.rules.global': 'Global',
  'ec.monitor.dashboard.rules.conditions': 'Conditions',
  'ec.monitor.dashboard.rules.duration': 'Duration/window (sec)',
  'ec.monitor.dashboard.rules.target': 'Target',
  'ec.monitor.dashboard.rules.partition': 'Partition',
  'ec.monitor.dashboard.rules.metric.cpu': 'CPU usage (%)',
  'ec.monitor.dashboard.rules.metric.memory': 'Memory usage (%)',
  'ec.monitor.dashboard.rules.metric.disk': 'Disk usage (%)',
  'ec.monitor.dashboard.rules.metric.partition': 'Partition free space (MB)',
  'ec.monitor.dashboard.rules.metric.process': 'Process abnormal',
  'ec.monitor.dashboard.rules.metric.offline': 'Agent offline',
  'ec.monitor.dashboard.rules.metric.logCritical': 'Critical log hits',
  'ec.monitor.dashboard.rules.metric.logTotal': 'Total log hits',
  'ec.monitor.dashboard.rules.operator.gt': 'Greater than',
  'ec.monitor.dashboard.rules.operator.gte': 'Greater than or equal',
  'ec.monitor.dashboard.rules.operator.lt': 'Less than',
  'ec.monitor.dashboard.rules.operator.lte': 'Less than or equal',
  'ec.monitor.dashboard.rules.operator.eq': 'Equal',
  'ec.monitor.dashboard.rules.message.loadFailed': 'Failed to load rules',
  'ec.monitor.dashboard.rules.message.detailFailed': 'Failed to load agent detail',
  'ec.monitor.dashboard.rules.message.ruleNameRequired': 'Rule name is required',
  'ec.monitor.dashboard.rules.message.groupRequired': 'At least one condition is required',
  'ec.monitor.dashboard.rules.message.createSuccess': 'Rule created',
  'ec.monitor.dashboard.rules.message.createFailed': 'Failed to create rule',
  'ec.monitor.dashboard.rules.message.deleteSuccess': 'Rule deleted',
  'ec.monitor.dashboard.rules.message.deleteConfirm': 'Delete the current rule?',
  'ec.monitor.dashboard.rules.message.cooldownWarning': 'Cooldown is lower than the agent report interval (60s). Actual precision will be limited by the report interval. Continue?',
  'ec.monitor.dashboard.rules.message.durationWarning': 'Some duration/window values are lower than the agent report interval (60s). Actual precision will be limited by the report interval. Continue?',
  'ec.monitor.dashboard.rules.message.helper': 'Detection precision depends on the agent report interval. Duration and cooldown values of 60s or above are recommended.',
  'ec.monitor.dashboard.logMonitor.title': 'Log monitors - {agentId}',
  'ec.monitor.dashboard.logMonitor.running': 'Running',
  'ec.monitor.dashboard.logMonitor.stopped': 'Stopped',
  'ec.monitor.dashboard.logMonitor.fileCount': '{count} files',
  'ec.monitor.dashboard.logMonitor.empty': 'No log monitor paths configured for this agent',
  'ec.monitor.dashboard.logMonitor.appName': 'Application',
  'ec.monitor.dashboard.logMonitor.appNamePlaceholder': 'Example: Payment service',
  'ec.monitor.dashboard.logMonitor.path': 'Monitor path',
  'ec.monitor.dashboard.logMonitor.pathPlaceholder': 'Example: D:\\logs\\*.log',
  'ec.monitor.dashboard.logMonitor.cancel': 'Cancel',
  'ec.monitor.dashboard.logMonitor.create': 'Add monitor',
  'ec.monitor.dashboard.logMonitor.delete': 'Remove',
  'ec.monitor.dashboard.logMonitor.unknownApp': 'Unknown application',
  'ec.monitor.dashboard.logMonitor.message.loadFailed': 'Failed to load log monitors',
  'ec.monitor.dashboard.logMonitor.message.pathRequired': 'Monitor path is required',
  'ec.monitor.dashboard.logMonitor.message.createSuccess': 'Log monitor created',
  'ec.monitor.dashboard.logMonitor.message.createFailed': 'Failed to create log monitor',
  'ec.monitor.dashboard.logMonitor.message.deleteSuccess': 'Log monitor removed',
  'ec.monitor.dashboard.logMonitor.message.deleteFailed': 'Failed to remove log monitor',
  'ec.monitor.dashboard.filterRule.title': 'Log filter rules - {agentId}',
  'ec.monitor.dashboard.filterRule.global': 'Global',
  'ec.monitor.dashboard.filterRule.empty': 'No dedicated filter rules for this agent',
  'ec.monitor.dashboard.filterRule.ruleName': 'Rule name',
  'ec.monitor.dashboard.filterRule.ruleNamePlaceholder': 'Example: Ignore heartbeat logs',
  'ec.monitor.dashboard.filterRule.ruleType': 'Rule type',
  'ec.monitor.dashboard.filterRule.ruleTypeCritical': 'Escalate to critical',
  'ec.monitor.dashboard.filterRule.ruleTypeExclude': 'Exclude directly',
  'ec.monitor.dashboard.filterRule.ruleTypeBasic': 'Basic record',
  'ec.monitor.dashboard.filterRule.matchMode': 'Match mode',
  'ec.monitor.dashboard.filterRule.matchContains': 'Contains',
  'ec.monitor.dashboard.filterRule.matchEquals': 'Equals',
  'ec.monitor.dashboard.filterRule.matchRegex': 'Regex',
  'ec.monitor.dashboard.filterRule.matchStartsWith': 'Starts with',
  'ec.monitor.dashboard.filterRule.matchEndsWith': 'Ends with',
  'ec.monitor.dashboard.filterRule.keyword': 'Keyword / expression',
  'ec.monitor.dashboard.filterRule.keywordPlaceholder': 'Enter match text',
  'ec.monitor.dashboard.filterRule.cancel': 'Cancel',
  'ec.monitor.dashboard.filterRule.create': 'Submit rule',
  'ec.monitor.dashboard.filterRule.delete': 'Delete',
  'ec.monitor.dashboard.filterRule.message.loadFailed': 'Failed to load filter rules',
  'ec.monitor.dashboard.filterRule.message.formRequired': 'Rule name and keyword are required',
  'ec.monitor.dashboard.filterRule.message.createSuccess': 'Filter rule created',
  'ec.monitor.dashboard.filterRule.message.createFailed': 'Failed to create filter rule',
  'ec.monitor.dashboard.filterRule.message.deleteSuccess': 'Filter rule deleted',
  'ec.monitor.dashboard.filterRule.message.deleteFailed': 'Failed to delete filter rule',
  'ec.monitor.dashboard.ttyd.title': 'TTYD - {agentId}',
  'ec.monitor.dashboard.ttyd.running': 'Running',
  'ec.monitor.dashboard.ttyd.stopped': 'Stopped',
  'ec.monitor.dashboard.ttyd.empty': 'No running TTYD services',
  'ec.monitor.dashboard.ttyd.portLabel': 'Port {port}',
  'ec.monitor.dashboard.ttyd.serviceMeta': 'Writable: {writable} | Workdir: {workingDirectory}',
  'ec.monitor.dashboard.ttyd.open': 'Open',
  'ec.monitor.dashboard.ttyd.stop': 'Stop',
  'ec.monitor.dashboard.ttyd.port': 'Port',
  'ec.monitor.dashboard.ttyd.writable': 'Writable',
  'ec.monitor.dashboard.ttyd.username': 'Username',
  'ec.monitor.dashboard.ttyd.password': 'Password',
  'ec.monitor.dashboard.ttyd.cancel': 'Cancel',
  'ec.monitor.dashboard.ttyd.start': 'Start and open',
  'ec.monitor.dashboard.ttyd.message.loadFailed': 'Failed to load TTYD services',
  'ec.monitor.dashboard.ttyd.message.invalidPort': 'Port must be an integer between 1 and 65535',
  'ec.monitor.dashboard.ttyd.message.usernameRequired': 'Username is required',
  'ec.monitor.dashboard.ttyd.message.passwordRequired': 'Password is required',
  'ec.monitor.dashboard.ttyd.message.linkMissing': 'TTYD started, but no accessible URL was returned',
  'ec.monitor.dashboard.ttyd.message.startSuccess': 'TTYD started',
  'ec.monitor.dashboard.ttyd.message.startFailed': 'Failed to start TTYD',
  'ec.monitor.dashboard.ttyd.message.stopConfirm': 'Stop the TTYD service on port {port}?',
  'ec.monitor.dashboard.ttyd.message.stopSuccess': 'TTYD stopped',
  'ec.monitor.dashboard.ttyd.message.stopFailed': 'Failed to stop TTYD',
  'ec.monitor.logs.form.agentId': 'Server',
  'ec.monitor.logs.form.agentId.placeholder': 'Enter agent identifier',
  'ec.monitor.logs.form.level': 'Alert level',
  'ec.monitor.logs.form.level.placeholder': 'Select alert level',
  'ec.monitor.logs.form.keyword': 'Keyword',
  'ec.monitor.logs.form.keyword.placeholder': 'Search content, rule, or application',
  'ec.monitor.logs.button.refresh': 'Refresh',
  'ec.monitor.logs.summary.critical': 'Critical alerts',
  'ec.monitor.logs.summary.unknownError': 'Common matches',
  'ec.monitor.logs.summary.total': 'Current results',
  'ec.monitor.logs.table.time': 'Time',
  'ec.monitor.logs.table.agentId': 'Server',
  'ec.monitor.logs.table.appName': 'Application',
  'ec.monitor.logs.table.level': 'Level',
  'ec.monitor.logs.table.rule': 'Matched rule',
  'ec.monitor.logs.table.content': 'Log summary',
  'ec.monitor.logs.detail.title': 'Log audit detail',
  'ec.monitor.logs.detail.agentId': 'Agent ID',
  'ec.monitor.logs.detail.appName': 'Application',
  'ec.monitor.logs.detail.logPath': 'Log path',
  'ec.monitor.logs.detail.rule': 'Matched rule',
  'ec.monitor.logs.detail.content': 'Raw log content',
  'ec.monitor.logs.level.all': 'All',
  'ec.monitor.logs.level.critical': 'Critical',
  'ec.monitor.logs.level.unknownError': 'Common match',
  'ec.monitor.logs.empty': 'No log records matched the current filters',
  'ec.monitor.logs.message.loadFailed': 'Failed to load log data',
  'ec.monitor.logs.message.detailFailed': 'Failed to load log detail',
}
