import Http from '@/utils/http'
import { AUTH_LOGIN_MODE } from '@/configs'

const LOCAL_LOGIN_USERS = {
  platformadmin: {
    password: '21232f297a57a5a743894a0e4a801fc3',
    token: 'local-admin-token',
    user: {
      id: 'local-admin-user',
      name: '平台管理员',
      organName: '信息化资产管理中心',
      username: 'platformadmin',
      avatar: '',
      role: 'AUTH_SYSTEM_ADMIN,ROLE_SYSTEM',
      permission: 'LIST.ADD,LIST.EDIT,LIST.DELETE,USER.ADD,USER.EDIT,USER.DELETE',
    },
  },
  eam_figma_demo: {
    password: 'e10adc3949ba59abbe56e057f20f883e',
    token: 'local-asset-figma-demo-token',
    user: {
      id: 'local-asset-figma-demo-user',
      name: '资产新版演示账号',
      organName: '资产新版正式入口',
      username: 'eam_figma_demo',
      avatar: '',
      role: 'ROLE_EAM_FIGMA',
      permission: '',
    },
  },
  ops_demo: {
    password: 'e10adc3949ba59abbe56e057f20f883e',
    token: 'local-operations-demo-token',
    user: {
      id: 'local-operations-demo-user',
      name: '运营管理演示账号',
      organName: '运营管理系统',
      username: 'ops_demo',
      avatar: '',
      role: 'ROLE_EAM_OPERATIONS',
      permission: '',
    },
  },
}

export const apiUserLogin = (params) => {
  if (AUTH_LOGIN_MODE === 'local') {
    const localUser = LOCAL_LOGIN_USERS[params?.username]
    if (localUser && localUser.password === params?.password) {
      return Promise.resolve({
        flag: true,
        msg: '登录成功',
        token: localUser.token,
        user: localUser.user,
      })
    }
  }

  return Http.request({
    url: '/bspplus/user/login',
    data: params,
    method: 'POST',
  })
  // return {
  //   flag: true,
  //   user: {
  //     role: 'AUTH_SYSTEM_ADMIN,ROLE_SYSTEM',
  //     isInitialPassword: '0',
  //     regionName: '中华人民共和国',
  //     mobile: '15165105355',
  //     appCode: 'CONSOLE-DG-ADMIN-SYSTEM',
  //     lastLoginTime: 1736157570000,
  //     organName: 'ec.user.info.organName',
  //     regionCode: '000000000000',
  //     phone: '',
  //     expirationTime: 4,
  //     organCode: '10100000',
  //     name: 'ec.user.info.username',
  //     id: '1prn2i69-2drs-c340-wbd9-wryg80l0upvi',
  //     email: 'gossiwang@gmail.com',
  //     username: 'platformadmin',
  //     avatar: '',
  //     permission: 'LIST.ADD,LIST.EDIT,LIST.DELETE,USER.ADD,USER.EDIT,USER.DELETE',
  //     dashboard: 'WELCOME,VERSION,CHART,ABOUT',
  //   },
  //   token:
  //     'eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLlubPlj7DnrqHnkIblkZgiLCJhdWQiOiI4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OCIsInNlcnZlciI6Imh0dHA6Ly9sb2NhbGhvc3Q6MjgwMC8iLCJyb2xlIjoiQVVUSF9TWVNURU1fQURNSU4sUk9MRV9TWVNURU0iLCJpc0luaXRpYWxQYXNzd29yZCI6IjAiLCJyZWdpb25OYW1lIjoi5Lit5Y2O5Lq65rCR5YWx5ZKM5Zu9IiwiaW5kdXN0cnkiOm51bGwsImFwcENvZGUiOiJDT05TT0xFLURHLUFETUlOLVNZU1RFTSIsIm9yZ2FuTmFtZSI6IuWbveWKoemZouWKnuWFrOWOheeUteWtkOaUv-WKoeWKniIsInJlZ2lvbkNvZGUiOiIwMDAwMDAwMDAwMDAiLCJpbmR1c3RyeUxpc3QiOm51bGwsImV4cGlyYXRpb25UaW1lIjo0LCJvcmdhbkNvZGUiOiIxMDEwMDAwMCIsImdyYWRlIjoiMSIsInN0YXR1cyI6IjEiLCJpc3MiOiJpbnNwdXIiLCJpYXQiOjE3MzYxNTgxMzMsImV4cCI6MTczNjE4NjkzM30.gY-pVnSRG-6m29XhwFtbjOKFF3-Iltk5HluoyP_KO6MuQrKVpwI89jS4jIi5IAe3WL1CFm4Ugq3PQb960RwjbA',
  //   refreshToken:
  //     'eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLlubPlj7DnrqHnkIblkZgiLCJhdWQiOiI4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OCIsInNlcnZlciI6Imh0dHA6Ly9sb2NhbGhvc3Q6MjgwMC8iLCJyb2xlIjoiQVVUSF9TWVNURU1fQURNSU4sUk9MRV9TWVNURU0iLCJpc0luaXRpYWxQYXNzd29yZCI6IjAiLCJyZWdpb25OYW1lIjoi5Lit5Y2O5Lq65rCR5YWx5ZKM5Zu9IiwiaW5kdXN0cnkiOm51bGwsImFwcENvZGUiOiJDT05TT0xFLURHLUFETUlOLVNZU1RFTSIsIm9yZ2FuTmFtZSI6IuWbveWKoemZouWKnuWFrOWOheeUteWtkOaUv-WKoeWKniIsInJlZ2lvbkNvZGUiOiIwMDAwMDAwMDAwMDAiLCJpbmR1c3RyeUxpc3QiOm51bGwsImV4cGlyYXRpb25UaW1lIjo0LCJvcmdhbkNvZGUiOiIxMDEwMDAwMCIsImdyYWRlIjoiMSIsInN0YXR1cyI6IjEiLCJpc3MiOiJpbnNwdXIiLCJqdGkiOiI4OTgzMDRiOS0zYTZkLTQ3ODktYThkNC0xNWU5OGVjZTQzNTkiLCJpYXQiOjE3MzYxNTgxMzMsImV4cCI6MTczNjE4ODEzM30.rSfWlLSkkgPDEMSFPIzkFwItyzqEXd8mSjNNrf43UFR4n_eh-S_OozfeyZROrV17Dvd-J6r8gSySlVXpw1atpQ',
  // }
}

export const apiUtilsUuid = () => {
  return Http.request(
    {
      url: '/bspplus/utils/uuid',
      method: 'GET',
    },
    true,
  )
}
export const apiUtilsSendSlideCode = () => {
  if (AUTH_LOGIN_MODE === 'local') {
    return Promise.resolve({ flag: true })
  }

  return Http.request({
    url: '/bspplus/utils/send/slideCode',
    method: 'GET',
  })
}
export const apiUserModifyPwd = (originPwd, newPwd) => {
  return Http.request({
    url: '/bspplus/user/modifyPwd',
    method: 'POST',
    data: { originPwd, newPwd },
  })
}
export const apiUserMenus = () => {
  // return Http.request({
  //   url: '/bspplus/user/menus',
  //   method: 'POST',
  //   data: {
  //     appCode: import.meta.env.VITE_APP_CODE,
  //     level: '3',
  //   },
  // })
  // 当前BSP的菜单数据是vue2版本的演示数据，跟现在组件命名不匹配，故使用模拟的BSP数据（后续需要重新bsp配一套）
  return [
    {
      path: '/home',
      data: 'home',
      hidden: 0,
      icon: 'home-smile-2-line',
      title: '主页',
      type: '2',
    },
    {
      path: '#',
      data: 'dashboard',
      hidden: 0,
      icon: 'dashboard-3-line',
      title: '控制台',
      type: '2',
      children: [
        {
          path: '/dashboard/dashboardWorkbench',
          data: 'dashboardWorkbench',
          hidden: 0,
          title: '主控台',
          type: '2',
        },
        {
          path: '/dashboard/dashboardConsole',
          data: 'dashboardConsole',
          hidden: 0,
          title: '主控台',
          type: '2',
        },
        {
          path: '/dashboard/dashboardCustom',
          data: 'dashboardCustom',
          hidden: 0,
          title: '自定义面板',
          type: '2',
        },
        {
          path: '/dashboard/dashboardExample',
          data: 'dashboardExample',
          hidden: 0,
          title: '组件测试面板',
          type: '2',
        },
      ],
    },
    {
      path: '#',
      data: 'basic',
      hidden: 0,
      icon: 'pencil-ruler-2-line',
      title: '基础项',
      type: '2',
      children: [
        {
          path: '/basic/basicColor',
          data: 'basicColor',
          hidden: 0,
          title: '色彩',
          type: '2',
        },
        {
          path: '/basic/basicLayout',
          data: 'basicLayout',
          hidden: 0,
          title: '布局',
          type: '2',
        },
        {
          path: '/basic/basicIcon',
          data: 'basicIcon',
          hidden: 0,
          title: '图标',
          type: '2',
        },
        {
          path: '/basic/basicButton',
          data: 'basicButton',
          hidden: 0,
          title: '按钮',
          type: '2',
        },
        {
          path: '/basic/basicLink',
          data: 'basicLink',
          hidden: 0,
          title: '文字链接',
          type: '2',
        },
      ],
    },
    {
      path: '#',
      data: 'form',
      hidden: 0,
      icon: 'input-field',
      title: '表单',
      type: '2',
      children: [
        {
          path: '/form/formBasic',
          data: 'formBasic',
          hidden: 0,
          title: '基础表单',
          type: '2',
        },
        {
          path: '/form/formGrid',
          data: 'formGrid',
          hidden: 0,
          title: '网格表单',
          type: '2',
        },
        {
          path: '/form/formStep',
          data: 'formStep',
          hidden: 0,
          title: '步骤表单',
          type: '2',
        },
        {
          path: '/form/formGroup',
          data: 'formGroup',
          hidden: 0,
          title: '分组表单',
          type: '2',
        },
        {
          path: '/form/formRender',
          data: 'formRender',
          hidden: 0,
          title: '低代码表单渲染器',
          type: '2',
        },
      ],
    },
    {
      path: '#',
      data: 'table',
      hidden: 0,
      icon: 'table-line',
      title: '表格',
      type: '2',
      children: [
        {
          path: '/table/tableBasic',
          data: 'tableBasic',
          hidden: 0,
          title: '基础表格',
          type: '2',
        },
        {
          path: '/table/tableAdvanced',
          data: 'tableAdvanced',
          hidden: 0,
          title: '高级表格',
          type: '2',
        },
        {
          path: '/table/tableEdit',
          data: 'tableEdit',
          hidden: 0,
          title: '行内编辑表格',
          type: '2',
        },
        {
          path: '/table/tableTabs',
          data: 'tableTabs',
          hidden: 0,
          title: '页签表格',
          type: '2',
        },
        {
          path: '/table/tableLayout',
          data: 'tableLayout',
          hidden: 0,
          title: '布局表格',
          type: '2',
        },
        {
          path: '/table/tableLowcode',
          data: 'tableLowcode',
          hidden: 0,
          title: '低代码表格',
          type: '2',
        },
      ],
    },
    {
      path: '#',
      data: 'vab',
      hidden: 0,
      icon: 'shapes-line',
      title: '原子组件',
      type: '2',
      tag: 'NEW',
      children: [
        {
          path: '/vab/vabChart',
          data: 'vabChart',
          title: '图表',
          type: '2',
        },
        {
          path: '/vab/vabIconSelect',
          data: 'vabIconSelect',
          hidden: 0,
          title: '图标选择器',
          type: '2',
        },
        {
          path: '/vab/vabTableSelect',
          data: 'vabTableSelect',
          hidden: 0,
          title: '表格选择器',
          type: '2',
        },
        {
          path: '/vab/vabAsyncLoad',
          data: 'vabAsyncLoad',
          hidden: 0,
          title: '异步加载',
          type: '2',
        },
        {
          path: '/vab/vabSelectFilter',
          data: 'vabSelectFilter',
          hidden: 0,
          title: '分类筛选器',
          type: '2',
        },
        {
          path: '/vab/vabTableFilter',
          data: 'vabTableFilter',
          hidden: 0,
          title: '动态过滤器',
          type: '2',
        },
        {
          path: '/vab/vabQrcode',
          data: 'vabQrcode',
          hidden: 0,
          title: '二维码',
          type: '2',
        },
        {
          path: '/vab/vabVideo',
          data: 'vabVideo',
          hidden: 0,
          title: '视频播放器',
          type: '2',
        },
        {
          path: '/vab/vabPrint',
          data: 'vabPrint',
          hidden: 0,
          title: '打印',
          type: '2',
        },
        {
          path: '/vab/vabCountup',
          data: 'vabCountup',
          hidden: 0,
          title: '数字自增长',
          type: '2',
        },
        {
          path: '/vab/vabWatermark',
          data: 'vabWatermark',
          hidden: 0,
          title: '水印',
          type: '2',
        },
        {
          path: '/vab/vabFileExport',
          data: 'vabFileExport',
          hidden: 0,
          title: '文件导出',
          type: '2',
        },
        {
          path: '/vab/vabFileImport',
          data: 'vabFileImport',
          hidden: 0,
          title: '文件导入',
          type: '2',
        },
        {
          path: '/vab/vabFileUpload',
          data: 'vabFileUpload',
          hidden: 0,
          title: '上传',
          type: '2',
        },
        {
          path: '/vab/vabMagnifier',
          data: 'vabMagnifier',
          hidden: 0,
          title: '放大镜',
          type: '2',
        },
        {
          path: '/vab/vabCropper',
          data: 'vabCropper',
          hidden: 0,
          title: '图像裁剪',
          type: '2',
        },
        {
          path: '/vab/vabContextmenu',
          data: 'vabContextmenu',
          hidden: 0,
          title: '右键菜单',
          type: '2',
        },
        {
          path: '/vab/vabCron',
          data: 'vabCron',
          hidden: 0,
          title: '规则生成器',
          type: '2',
        },
        {
          path: '/vab/vabCodeeditor',
          data: 'vabCodeeditor',
          hidden: 0,
          title: '代码编辑器',
          type: '2',
        },
        {
          path: '/vab/vabPasswordStrength',
          data: 'vabPasswordStrength',
          hidden: 0,
          title: '密码强度检测器',
          type: '2',
        },
        {
          path: '/vab/vabEditor',
          data: 'vabEditor',
          hidden: 0,
          title: '富文本编辑器',
          type: '2',
        },
        {
          path: '/vab/vabDraggable',
          data: 'vabDraggable',
          hidden: 0,
          title: '拖拽',
          type: '2',
        },
        {
          path: '/vab/vabTrend',
          data: 'vabTrend',
          hidden: 0,
          title: '趋势指示器',
          type: '2',
        },
        {
          path: '/vab/vabAsyncSelect',
          data: 'vabAsyncSelect',
          hidden: 0,
          title: '异步选择器',
          type: '2',
        },
        {
          path: '/vab/vabDirective',
          data: 'vabDirective',
          hidden: 0,
          title: '指令集合',
          type: '2',
        },
        {
          path: '/vab/vabEsign',
          data: 'vabEsign',
          hidden: 0,
          title: '电子签名',
          type: '2',
        },
        {
          path: '/vab/vabImageViewer',
          data: 'vabImageViewer',
          hidden: 0,
          title: '图片预览器',
          type: '2',
          tag: 'NEW',
        },
        {
          path: '/vab/vab-dynamic-icon',
          data: 'vabDynamicIcon',
          hidden: 0,
          title: '动效图标',
          type: '2',
          tag: 'NEW',
        },
        {
          path: '/vab/vab-milestone',
          data: 'vabMilestone',
          hidden: 0,
          children: null,
          icon: null,
          menuId: 'a3d260b6-ae1b-a3be-4201-d3116846da11',
          title: '里程碑',
          type: '2',
          tag: 'NEW',
        },
      ],
    },
    {
      path: '#',
      data: 'biz',
      hidden: 0,
      icon: 'briefcase-4-line',
      menuId: '2238dea2-58d8-bc5f-b5f4-ee86d1ac03fc',
      title: '业务组件',
      type: '2',
      tag: 'NEW',
      children: [
        {
          path: '/biz/biz-map',
          data: 'bizMap',
          hidden: 0,
          children: null,
          icon: null,
          menuId: '9d19e5ef-5ba6-14df-e20a-acdd2ec63ff2',
          title: '百度地图',
          type: '2',
        },
        {
          path: '/biz/biz-situation-guide',
          data: 'bizSituationGuide',
          hidden: 0,
          children: null,
          icon: null,
          menuId: '1a680558-33cf-de36-0df3-d6d12a302208',
          title: '引导式情形问答',
          type: '2',
        },
        {
          path: '/biz/biz-chat',
          data: 'bizChat',
          hidden: 0,
          children: null,
          icon: null,
          menuId: '9e89c39c-d5cc-ed1a-255b-381a5db3b5db',
          title: '模拟对话',
          type: '2',
          tag: 'NEW',
        },
        {
          path: '/biz/biz-tag-manage',
          data: 'bizTagManage',
          hidden: 0,
          children: null,
          icon: null,
          menuId: '7703d3b0-cbce-1f03-5ac3-8f9cab0f3551',
          title: '标签管理',
          type: '2',
          tag: 'NEW',
        },
        {
          path: '/biz/biz-sms-manage',
          data: 'bizSmsManage',
          hidden: 0,
          children: null,
          icon: null,
          menuId: 'e663643d-b3ff-2c4c-2760-8ae3076b0fd8',
          title: '短信模版管理',
          type: '2',
          tag: 'NEW',
        },
        {
          path: '/biz/biz-tree-extend',
          data: 'bizTreeExtend',
          hidden: 0,
          children: null,
          icon: null,
          menuId: '47926039-ee4a-b1bd-8c77-645ac7a6aa96',
          title: '树形扩展',
          type: '2',
          tag: 'NEW',
        },
        {
          path: '/biz/biz-pdf',
          data: 'bizPdf',
          hidden: 0,
          children: null,
          icon: null,
          menuId: 'aded43c2-365e-4457-8420-544894694d83',
          title: 'Pdf编辑器',
          type: '2',
          tag: 'NEW',
        },
        {
          path: '/biz/biz-resource',
          data: 'bizResource',
          hidden: 0,
          children: null,
          icon: null,
          menuId: 'e0150e69-adc2-8c3f-124f-68fbd5c99614',
          title: '资产管理器',
          type: '2',
        },
        {
          path: '/biz/biz-workflow',
          data: 'bizWorkflow',
          hidden: 0,
          children: null,
          icon: null,
          menuId: 'cd0cfcdd-7b37-4ba8-839c-f76a9139576e',
          title: '工作流',
          type: '2',
        },
        {
          path: '/biz/biz-form-design',
          data: 'bizFormDesign',
          hidden: 0,
          children: null,
          icon: null,
          menuId: '8bb1b1ac-33ef-6f6f-11e6-e99fd6a16527',
          title: '表单设计器',
          type: '2',
        },
        {
          path: '/biz/biz-wujie',
          data: 'bizWujie',
          hidden: 0,
          children: null,
          icon: null,
          menuId: '36738eb3-f25e-fb34-4f80-b6946ede00ed',
          title: '无界微前端',
          type: '2',
        },
        {
          path: '/biz/biz-canvas-editor',
          data: 'bizCanvasEditor',
          hidden: 0,
          children: null,
          icon: null,
          menuId: '6ff6f5a6-0b23-3b9d-2c33-a75b0ee31d55',
          title: '在线文档编辑器',
          type: '2',
        },
        {
          path: '/biz/biz-upload',
          data: 'bizUpload',
          hidden: 0,
          children: null,
          icon: null,
          menuId: 'dccef621-0579-2a37-844c-3eaae81f1df1',
          title: '本地上传',
          type: '2',
        },
        {
          path: '/biz/biz-tour',
          data: 'bizTour',
          hidden: 0,
          children: null,
          icon: null,
          menuId: '1aef8a92-358f-aac4-ab57-d7544ea92caf',
          title: '漫游式引导',
          type: '2',
          tag: 'NEW',
        },
        {
          path: '/biz/biz-eloam',
          data: 'bizEloam',
          hidden: 0,
          children: null,
          icon: null,
          menuId: '2f1a71fb-a3ba-a81d-5a85-3c04e5b44c56',
          title: '良田高拍仪',
          type: '2',
          tag: 'NEW',
        },
        {
          path: '/biz/biz-flight',
          data: 'bizFlight',
          hidden: 0,
          children: null,
          icon: null,
          menuId: '1e052af6-2881-c235-47b1-6b6a64a252be',
          title: '飞机选座',
          type: '2',
          tag: 'NEW',
        },
        {
          path: '/biz/biz-path-find',
          data: 'bizPathFind',
          hidden: 0,
          children: null,
          icon: null,
          menuId: '807e85ec-7b1b-2134-be00-31b0960ec96a',
          title: '寻路',
          type: '2',
          tag: 'NEW',
        },
      ],
    },
    {
      path: '#',
      data: 'list',
      hidden: 0,
      icon: 'list-check',
      menuId: 'c4477839-6b4e-5903-9b87-585e84533baf',
      title: '列表页',
      type: '2',
      children: [
        {
          path: '/list/list-basic',
          data: 'listBasic',
          hidden: 0,
          children: null,
          icon: null,
          menuId: '3dc8e51d-0a66-a7af-fb8a-fca2e5b5c3de',
          title: '基础列表',
          type: '2',
        },
        {
          path: '/list/list-article',
          data: 'listArticle',
          hidden: 0,
          children: null,
          icon: null,
          menuId: 'deb63c40-ed3a-a1a5-ff36-f32868a71d83',
          title: '文章列表',
          type: '2',
        },
        {
          path: '/list/list-card',
          data: 'listCard',
          hidden: 0,
          children: null,
          icon: null,
          menuId: 'abfdb271-c8c4-bf4e-82cc-059ae465b25f',
          title: '卡片列表',
          type: '2',
        },
        {
          path: '/list/list-tree',
          data: 'listTree',
          hidden: 0,
          children: null,
          icon: null,
          menuId: 'dece01e3-00c1-a37b-aadb-e96e920a65aa',
          remark: null,
          title: '树形分类列表',
          type: '2',
        },
        {
          path: '/list/list-toggle',
          data: 'listToggle',
          hidden: 0,
          children: null,
          icon: null,
          menuId: '9cf273bb-80e0-66f5-aef8-7dadfe5e479a',
          remark: null,
          title: '列表卡片切换',
          type: '2',
        },
      ],
    },
    {
      path: '#',
      data: 'detail',
      hidden: 0,
      icon: 'profile-line',
      menuId: '9807659d-bab1-b848-33b0-a28f2fe58de7',
      title: '详情页',
      type: '2',
      children: [
        {
          path: '/detail/detail-basic',
          data: 'detailBasic',
          hidden: 0,
          children: null,
          icon: null,
          menuId: '7928cd01-bd54-9a84-aff2-9e8a1667b717',
          title: '基础详情',
          type: '2',
        },
        {
          path: '/detail/detail-drawer',
          data: 'detailDrawer',
          hidden: 0,
          children: null,
          icon: null,
          menuId: '7945725a-0d6a-9ab1-a71d-14d24b9556c4',
          remark: null,
          title: '抽屉详情',
          type: '2',
        },
        {
          path: '/detail/detail-dialog',
          data: 'detailDialog',
          hidden: 0,
          children: null,
          icon: null,
          menuId: '113ceb93-8495-00a8-c410-acfafd43b3e2',
          remark: null,
          title: '弹窗详情',
          type: '2',
        },
        {
          path: '/detail/detail-article',
          data: 'detailArticle',
          hidden: 0,
          children: null,
          icon: null,
          menuId: '5e248dd2-9be9-ef2c-6126-3486fa133c36',
          remark: null,
          title: '文章详情',
          type: '2',
        },
      ],
    },
    {
      path: '#',
      data: 'result',
      hidden: 0,
      icon: 'checkbox-multiple-line',
      menuId: 'c038e654-73ed-91bf-2892-003e04f241c6',
      title: '结果页',
      type: '2',
      children: [
        {
          path: '/result/success',
          data: 'resultSuccess',
          hidden: 0,
          children: null,
          icon: null,
          menuId: 'decd16da-afd0-7c26-0844-d157eb36ca76',
          title: '成功页',
          type: '2',
        },
        {
          path: '/result/fail',
          data: 'resultFail',
          hidden: 0,
          children: null,
          icon: null,
          menuId: '9f984348-f33e-8571-76b2-9946ec8bba81',
          title: '失败页',
          type: '2',
        },
      ],
    },
    {
      path: '#',
      data: 'error',
      hidden: 0,
      icon: 'error-warning-line',
      menuId: '16c5536c-c0b5-4abc-a106-9f9531eae11c',
      title: '异常页',
      type: '2',
      children: [
        {
          path: '/error/404',
          data: 'error404',
          hidden: 0,
          children: null,
          icon: null,
          menuId: 'f193fbad-6e3b-013f-c11f-e7947109bdc3',
          title: '404',
          type: '2',
        },
        {
          path: '/error/500',
          data: 'error500',
          hidden: 0,
          children: null,
          icon: null,
          menuId: '4c7456ca-7c28-b3a8-1384-a8ef85315b08',
          title: '500',
          type: '2',
        },
        {
          path: '/error/403',
          data: 'error403',
          hidden: 0,
          children: null,
          icon: null,
          menuId: 'ef82750b-5b8a-6aa6-3d9d-0518a612c248',
          title: '403',
          type: '2',
        },
      ],
    },
    {
      path: '#',
      data: 'link',
      hidden: 0,
      icon: 'swap-2-line',
      menuId: 'b94b89c4-6d89-ea41-428d-927614c44441',
      title: '外部链接',
      type: '2',
      children: [
        {
          path: 'https://www.baidu.com/',
          data: 'linkBaidu',
          hidden: 0,
          children: null,
          icon: null,
          menuId: 'f5094414-4ae5-448a-710b-b0a9ea8b6e42',
          title: '百度',
          type: '1',
        },
        {
          path: '/link/link-segmentfault',
          data: 'linkSegmentfault',
          hidden: 0,
          children: null,
          icon: null,
          menuId: 'a12f79ff-9e93-4b97-9336-0173487acb6e',
          title: '思否',
          type: '2',
        },
      ],
    },

    {
      path: '#',
      data: 'city',
      hidden: 0,
      icon: 'stack-line',
      menuId: 'ee4d172a-cd27-cf3e-6524-5b94ab2fe03a',
      remark: null,
      title: '菜单层级',
      type: '2',
      children: [
        {
          path: '#',
          data: 'cityJiangxi',
          hidden: 0,
          icon: null,
          menuId: '2b612ef9-5ff4-f888-e112-32768d00a059',
          remark: null,
          title: '江西省',
          type: '2',
          children: [
            {
              path: '/city/jiangxi/nanchang',
              data: 'cityJiangxiNanchang',
              hidden: 0,
              icon: null,
              menuId: '9667f75c-e84b-ffdf-407a-d542f3d354c2',
              title: '南昌市',
              type: '2',
            },
            {
              path: '/city/jiangxi/yingtan',
              data: 'cityJiangxiYingtan',
              hidden: 0,
              icon: null,
              menuId: 'a56bf695-6010-b2c3-36a3-dc19a9ee27f4',
              title: '鹰潭市',
              type: '2',
            },
          ],
        },
        {
          path: '/city/chongqing',
          data: 'cityChongqing',
          hidden: 0,
          children: null,
          icon: null,
          menuId: '1aa7b43c-0e8b-9fef-a779-045c977332e0',
          remark: null,
          title: '重庆市',
          type: '2',
        },
        {
          path: '/city/shanghai',
          data: 'cityShanghai',
          hidden: 0,
          icon: null,
          menuId: '6269094e-faed-ed7e-7e4b-f46f565cf8fd',
          remark: null,
          title: '上海市',
          type: '2',
          children: [
            {
              path: '/city/shanghai/jingan',
              data: 'cityShanghaiJingan',
              hidden: 1,
              icon: null,
              menuId: 'dk88375c-209d-llk8-200j-d52929jjdhu0',
              title: '静安区',
              type: '2',
            },
          ],
        },
      ],
    },
  ]
}
