export default {
  'ec.menu.name.organization': 'Organization',
  'ec.menu.name.organizationDepartments': 'Departments',
  'ec.menu.name.organizationLocations': 'Locations',
  'ec.menu.name.organizationServiceProviders': 'Service Providers',
  'ec.menu.name.organizationPersons': 'Persons',

  'ec.organization.common.code': 'Code',
  'ec.organization.common.name': 'Name',
  'ec.organization.common.status': 'Status',
  'ec.organization.common.createdAt': 'Created At',
  'ec.organization.common.updatedAt': 'Updated At',
  'ec.organization.common.actions': 'Actions',
  'ec.organization.common.create': 'Create',
  'ec.organization.common.edit': 'Edit',
  'ec.organization.common.detail': 'Detail',
  'ec.organization.common.relations': 'Relations',
  'ec.organization.common.delete': 'Delete',
  'ec.organization.common.addChild': 'Add Child',
  'ec.organization.common.root': 'Top Level',
  'ec.organization.common.empty': 'No data available',
  'ec.organization.common.noRelation': 'No related data',
  'ec.organization.common.saveSuccess': 'Saved successfully',
  'ec.organization.common.saveFailed': 'Save failed',
  'ec.organization.common.deleteSuccess': 'Deleted successfully',
  'ec.organization.common.deleteFailed': 'Delete failed',
  'ec.organization.common.deleteConfirm': 'Are you sure you want to delete "{name}"?',

  'ec.organization.department.form.keyword': 'Keyword',
  'ec.organization.department.form.keywordPlaceholder': 'Search by code or name',
  'ec.organization.department.form.codePlaceholder': 'Enter department code',
  'ec.organization.department.form.namePlaceholder': 'Enter department name',
  'ec.organization.department.form.parentDepartment': 'Parent Department',
  'ec.organization.department.form.parentDepartmentPlaceholder': 'Leave empty for top level',
  'ec.organization.department.form.statusPlaceholder': 'Select department status',
  'ec.organization.department.table.parentName': 'Parent Department',
  'ec.organization.department.dialog.createTitle': 'Create Department',
  'ec.organization.department.dialog.editTitle': 'Edit Department',
  'ec.organization.department.drawer.title': 'Department Detail',
  'ec.organization.department.validation.codeRequired': 'Please enter the department code',
  'ec.organization.department.validation.nameRequired': 'Please enter the department name',
  'ec.organization.department.validation.statusRequired': 'Please select the department status',
  'ec.organization.department.message.loadFailed': 'Failed to load departments',
  'ec.organization.department.message.detailFailed': 'Failed to load department detail',

  'ec.organization.location.form.keyword': 'Keyword',
  'ec.organization.location.form.keywordPlaceholder': 'Search by location code or name',
  'ec.organization.location.form.codePlaceholder': 'Enter location code',
  'ec.organization.location.form.namePlaceholder': 'Enter location name',
  'ec.organization.location.form.sitePlaceholder': 'Enter site',
  'ec.organization.location.form.buildingPlaceholder': 'Enter building',
  'ec.organization.location.form.floorPlaceholder': 'Enter floor',
  'ec.organization.location.form.areaPlaceholder': 'Enter area',
  'ec.organization.location.form.addressDetailPlaceholder': 'Enter address detail',
  'ec.organization.location.table.site': 'Site',
  'ec.organization.location.table.building': 'Building',
  'ec.organization.location.table.floor': 'Floor',
  'ec.organization.location.table.area': 'Area',
  'ec.organization.location.table.addressDetail': 'Address Detail',
  'ec.organization.location.dialog.createTitle': 'Create Location',
  'ec.organization.location.dialog.editTitle': 'Edit Location',
  'ec.organization.location.drawer.title': 'Location Detail',
  'ec.organization.location.validation.codeRequired': 'Please enter the location code',
  'ec.organization.location.validation.nameRequired': 'Please enter the location name',
  'ec.organization.location.message.loadFailed': 'Failed to load locations',
  'ec.organization.location.message.detailFailed': 'Failed to load location detail',

  'ec.organization.serviceProvider.form.keyword': 'Keyword',
  'ec.organization.serviceProvider.form.keywordPlaceholder': 'Search by provider code or name',
  'ec.organization.serviceProvider.form.type': 'Type',
  'ec.organization.serviceProvider.form.typePlaceholder': 'Select provider type',
  'ec.organization.serviceProvider.form.status': 'Status',
  'ec.organization.serviceProvider.form.statusPlaceholder': 'Select provider status',
  'ec.organization.serviceProvider.form.codePlaceholder': 'Enter provider code',
  'ec.organization.serviceProvider.form.namePlaceholder': 'Enter provider name',
  'ec.organization.serviceProvider.form.unifiedSocialCreditCodePlaceholder': 'Enter unified social credit code',
  'ec.organization.serviceProvider.form.ratingLevelPlaceholder': 'Enter rating level',
  'ec.organization.serviceProvider.form.remarkPlaceholder': 'Enter remark',
  'ec.organization.serviceProvider.table.type': 'Provider Type',
  'ec.organization.serviceProvider.table.unifiedSocialCreditCode': 'Unified Social Credit Code',
  'ec.organization.serviceProvider.table.ratingLevel': 'Rating Level',
  'ec.organization.serviceProvider.table.remark': 'Remark',
  'ec.organization.serviceProvider.dialog.createTitle': 'Create Service Provider',
  'ec.organization.serviceProvider.dialog.editTitle': 'Edit Service Provider',
  'ec.organization.serviceProvider.dialog.relationsTitle': 'Manage Service Provider Relations',
  'ec.organization.serviceProvider.drawer.title': 'Service Provider Detail',
  'ec.organization.serviceProvider.validation.codeRequired': 'Please enter the provider code',
  'ec.organization.serviceProvider.validation.nameRequired': 'Please enter the provider name',
  'ec.organization.serviceProvider.validation.typeRequired': 'Please select the provider type',
  'ec.organization.serviceProvider.validation.statusRequired': 'Please select the provider status',
  'ec.organization.serviceProvider.message.loadFailed': 'Failed to load service providers',
  'ec.organization.serviceProvider.message.detailFailed': 'Failed to load service provider detail',
  'ec.organization.serviceProvider.relation.saveSuccess': 'Service provider relations saved successfully',
  'ec.organization.serviceProvider.relation.saveFailed': 'Failed to save service provider relations',
  'ec.organization.serviceProvider.relation.hardwareAssetsPlaceholder': 'Select hardware assets',
  'ec.organization.serviceProvider.relation.informationSystemsPlaceholder': 'Select systems',
  'ec.organization.serviceProvider.relation.personsPlaceholder': 'Select persons',
  'ec.organization.serviceProvider.type.supplier': 'Supplier',
  'ec.organization.serviceProvider.type.serviceProvider': 'Service Provider',
  'ec.organization.serviceProvider.type.integrator': 'Integrator',
  'ec.organization.serviceProvider.type.maintenance': 'Maintenance',
  'ec.organization.serviceProvider.relations.hardwareAssets': 'Hardware Assets',
  'ec.organization.serviceProvider.relations.informationSystems': 'Systems',
  'ec.organization.serviceProvider.relations.persons': 'Persons',
  'ec.organization.serviceProvider.relations.projects': 'Projects',

  'ec.organization.person.form.keyword': 'Keyword',
  'ec.organization.person.form.keywordPlaceholder': 'Search by name, employee no. or mobile',
  'ec.organization.person.form.department': 'Department',
  'ec.organization.person.form.departmentPlaceholder': 'Select department',
  'ec.organization.person.form.status': 'Status',
  'ec.organization.person.form.statusPlaceholder': 'Select person status',
  'ec.organization.person.form.namePlaceholder': 'Enter name',
  'ec.organization.person.form.genderPlaceholder': 'Enter gender',
  'ec.organization.person.form.idCardNoPlaceholder': 'Enter ID card no.',
  'ec.organization.person.form.mobilePlaceholder': 'Enter mobile',
  'ec.organization.person.form.employeeNoPlaceholder': 'Enter employee no.',
  'ec.organization.person.form.photoUrlPlaceholder': 'Enter photo URL',
  'ec.organization.person.form.accountPlaceholder': 'Enter account',
  'ec.organization.person.table.gender': 'Gender',
  'ec.organization.person.table.idCardNo': 'ID Card No.',
  'ec.organization.person.table.mobile': 'Mobile',
  'ec.organization.person.table.employeeNo': 'Employee No.',
  'ec.organization.person.table.photoUrl': 'Photo URL',
  'ec.organization.person.table.account': 'Account',
  'ec.organization.person.table.departmentName': 'Department',
  'ec.organization.person.dialog.createTitle': 'Create Person',
  'ec.organization.person.dialog.editTitle': 'Edit Person',
  'ec.organization.person.dialog.relationsTitle': 'Manage Person Relations',
  'ec.organization.person.drawer.title': 'Person Detail',
  'ec.organization.person.validation.nameRequired': 'Please enter the name',
  'ec.organization.person.validation.statusRequired': 'Please select the person status',
  'ec.organization.person.message.loadFailed': 'Failed to load persons',
  'ec.organization.person.message.detailFailed': 'Failed to load person detail',
  'ec.organization.person.message.departmentLoadFailed': 'Failed to load department options',
  'ec.organization.person.relation.saveSuccess': 'Person relations saved successfully',
  'ec.organization.person.relation.saveFailed': 'Failed to save person relations',
  'ec.organization.person.relation.hardwareAssetsPlaceholder': 'Select hardware assets',
  'ec.organization.person.relation.informationSystemsPlaceholder': 'Select systems',
  'ec.organization.person.relations.hardwareAssets': 'Hardware Assets',
  'ec.organization.person.relations.informationSystems': 'Systems',
  'ec.organization.person.relations.projects': 'Projects',
}
