export default {
  'ec.menu.name.organization': 'Organization',
  'ec.menu.name.organizationDepartments': 'Departments',
  'ec.menu.name.organizationLocations': 'Locations',
  'ec.menu.name.organizationServiceProviders': 'Service Providers',
  'ec.menu.name.organizationPersons': 'Persons',
  'ec.menu.name.organizationServiceProvidersFigma': 'Service Providers (Figma)',
  'ec.menu.name.organizationPersonsFigma': 'Persons (Figma)',

  'ec.organization.common.code': 'Code',
  'ec.organization.common.name': 'Name',
  'ec.organization.common.status': 'Status',
  'ec.organization.common.createdAt': 'Created At',
  'ec.organization.common.updatedAt': 'Updated At',
  'ec.organization.common.actions': 'Actions',
  'ec.organization.common.create': 'Create',
  'ec.organization.common.edit': 'Edit',
  'ec.organization.common.detail': 'Detail',
  'ec.organization.common.relations': 'Relations',
  'ec.organization.common.delete': 'Delete',
  'ec.organization.common.addChild': 'Add Child',
  'ec.organization.common.root': 'Top Level',
  'ec.organization.common.empty': 'No data available',
  'ec.organization.common.noRelation': 'No related data',
  'ec.organization.common.saveSuccess': 'Saved successfully',
  'ec.organization.common.saveFailed': 'Save failed',
  'ec.organization.common.deleteSuccess': 'Deleted successfully',
  'ec.organization.common.deleteFailed': 'Delete failed',
  'ec.organization.common.deleteConfirm': 'Are you sure you want to delete "{name}"?',
  'ec.organization.selector.searchPlaceholder': 'Please enter content',
  'ec.organization.selector.selected': 'Selected',
  'ec.organization.selector.titleSuffix': ' Selection',
  'ec.organization.figma.appTitle': 'Government Service Operations Platform',
  'ec.organization.figma.defaultUser': 'System Administrator',
  'ec.organization.figma.top.overview': 'Overview',
  'ec.organization.figma.top.service': 'Service Desk',
  'ec.organization.figma.top.monitor': 'Operations Monitoring',
  'ec.organization.figma.top.inspection': 'Operations Inspection',
  'ec.organization.figma.top.board': 'Data Board',
  'ec.organization.figma.top.config': 'Business Config',
  'ec.organization.figma.side.workbench': 'Asset Workbench',
  'ec.organization.figma.side.data': 'Data Assets',
  'ec.organization.figma.table.index': '#',
  'ec.organization.figma.tab.serviceProviders': 'Service Providers',
  'ec.organization.figma.tab.persons': 'Persons',

  'ec.organization.department.form.keyword': 'Keyword',
  'ec.organization.department.form.keywordPlaceholder': 'Search by code or name',
  'ec.organization.department.form.codePlaceholder': 'Enter department code',
  'ec.organization.department.form.namePlaceholder': 'Enter department name',
  'ec.organization.department.form.parentDepartment': 'Parent Department',
  'ec.organization.department.form.parentDepartmentPlaceholder': 'Leave empty for top level',
  'ec.organization.department.form.statusPlaceholder': 'Select department status',
  'ec.organization.department.table.parentName': 'Parent Department',
  'ec.organization.department.dialog.createTitle': 'Create Department',
  'ec.organization.department.dialog.editTitle': 'Edit Department',
  'ec.organization.department.drawer.title': 'Department Detail',
  'ec.organization.department.validation.codeRequired': 'Please enter the department code',
  'ec.organization.department.validation.nameRequired': 'Please enter the department name',
  'ec.organization.department.validation.statusRequired': 'Please select the department status',
  'ec.organization.department.message.loadFailed': 'Failed to load departments',
  'ec.organization.department.message.detailFailed': 'Failed to load department detail',

  'ec.organization.location.form.keyword': 'Keyword',
  'ec.organization.location.form.keywordPlaceholder': 'Search by location code or name',
  'ec.organization.location.form.codePlaceholder': 'Enter location code',
  'ec.organization.location.form.namePlaceholder': 'Enter location name',
  'ec.organization.location.form.sitePlaceholder': 'Enter site',
  'ec.organization.location.form.buildingPlaceholder': 'Enter building',
  'ec.organization.location.form.floorPlaceholder': 'Enter floor',
  'ec.organization.location.form.areaPlaceholder': 'Enter area',
  'ec.organization.location.form.addressDetailPlaceholder': 'Enter address detail',
  'ec.organization.location.table.site': 'Site',
  'ec.organization.location.table.building': 'Building',
  'ec.organization.location.table.floor': 'Floor',
  'ec.organization.location.table.area': 'Area',
  'ec.organization.location.table.addressDetail': 'Address Detail',
  'ec.organization.location.dialog.createTitle': 'Create Location',
  'ec.organization.location.dialog.editTitle': 'Edit Location',
  'ec.organization.location.drawer.title': 'Location Detail',
  'ec.organization.location.validation.codeRequired': 'Please enter the location code',
  'ec.organization.location.validation.nameRequired': 'Please enter the location name',
  'ec.organization.location.message.loadFailed': 'Failed to load locations',
  'ec.organization.location.message.detailFailed': 'Failed to load location detail',

  'ec.organization.serviceProvider.form.keyword': 'Keyword',
  'ec.organization.serviceProvider.form.keywordPlaceholder': 'Search by provider code or name',
  'ec.organization.serviceProvider.form.type': 'Type',
  'ec.organization.serviceProvider.form.typePlaceholder': 'Select provider type',
  'ec.organization.serviceProvider.form.cooperationScopePlaceholder': 'Select cooperation scope',
  'ec.organization.serviceProvider.form.status': 'Status',
  'ec.organization.serviceProvider.form.statusPlaceholder': 'Select provider status',
  'ec.organization.serviceProvider.form.codePlaceholder': 'Enter provider code',
  'ec.organization.serviceProvider.form.namePlaceholder': 'Enter provider name',
  'ec.organization.serviceProvider.form.shortName': 'Short Name',
  'ec.organization.serviceProvider.form.shortNamePlaceholder': 'Enter provider short name',
  'ec.organization.serviceProvider.form.logoUrl': 'Logo URL',
  'ec.organization.serviceProvider.form.logoUrlPlaceholder': 'Enter logo image URL',
  'ec.organization.serviceProvider.form.logoUpload': 'Upload Image',
  'ec.organization.serviceProvider.form.logoReplace': 'Replace Image',
  'ec.organization.serviceProvider.form.logoRemove': 'Remove Image',
  'ec.organization.serviceProvider.form.logoPreview': 'Logo Preview',
  'ec.organization.serviceProvider.form.unifiedSocialCreditCodePlaceholder': 'Enter unified social credit code',
  'ec.organization.serviceProvider.form.enterpriseNature': 'Enterprise Nature',
  'ec.organization.serviceProvider.form.enterpriseNaturePlaceholder': 'Select enterprise nature',
  'ec.organization.serviceProvider.form.vendorLevel': 'Vendor Level',
  'ec.organization.serviceProvider.form.vendorLevelPlaceholder': 'Select vendor level',
  'ec.organization.serviceProvider.form.businessContact': 'Business Contact',
  'ec.organization.serviceProvider.form.businessContactPlaceholder': 'Enter business contact',
  'ec.organization.serviceProvider.form.businessPhone': 'Business Phone',
  'ec.organization.serviceProvider.form.businessPhonePlaceholder': 'Enter business phone',
  'ec.organization.serviceProvider.form.ratingLevelPlaceholder': 'Enter rating level',
  'ec.organization.serviceProvider.form.remarkPlaceholder': 'Enter remark',
  'ec.organization.serviceProvider.table.type': 'Provider Type',
  'ec.organization.serviceProvider.table.unifiedSocialCreditCode': 'Unified Social Credit Code',
  'ec.organization.serviceProvider.table.cooperationScopes': 'Cooperation Scope',
  'ec.organization.serviceProvider.table.score': 'Score',
  'ec.organization.serviceProvider.table.ratingLevel': 'Rating Level',
  'ec.organization.serviceProvider.table.remark': 'Remark',
  'ec.organization.serviceProvider.dialog.createTitle': 'Create Service Provider',
  'ec.organization.serviceProvider.dialog.editTitle': 'Edit Service Provider',
  'ec.organization.serviceProvider.dialog.relationsTitle': 'Manage Service Provider Relations',
  'ec.organization.serviceProvider.drawer.title': 'Service Provider Detail',
  'ec.organization.serviceProvider.validation.codeRequired': 'Please enter the provider code',
  'ec.organization.serviceProvider.validation.nameRequired': 'Please enter the provider name',
  'ec.organization.serviceProvider.validation.typeRequired': 'Please select the provider type',
  'ec.organization.serviceProvider.validation.cooperationScopesRequired': 'Please select at least one cooperation scope',
  'ec.organization.serviceProvider.validation.statusRequired': 'Please select the provider status',
  'ec.organization.serviceProvider.message.loadFailed': 'Failed to load service providers',
  'ec.organization.serviceProvider.message.detailFailed': 'Failed to load service provider detail',
  'ec.organization.serviceProvider.relation.saveSuccess': 'Service provider relations saved successfully',
  'ec.organization.serviceProvider.relation.saveFailed': 'Failed to save service provider relations',
  'ec.organization.serviceProvider.relation.hardwareAssetsPlaceholder': 'Select hardware assets',
  'ec.organization.serviceProvider.relation.informationSystemsPlaceholder': 'Select systems',
  'ec.organization.serviceProvider.relation.personsPlaceholder': 'Select persons',
  'ec.organization.serviceProvider.relation.projectsPlaceholder': 'Select projects',
  'ec.organization.serviceProvider.type.supplier': 'Supplier',
  'ec.organization.serviceProvider.type.serviceProvider': 'Service Provider',
  'ec.organization.serviceProvider.type.integrator': 'Integrator',
  'ec.organization.serviceProvider.type.maintenance': 'Maintenance',
  'ec.organization.serviceProvider.scope.softwareDevelopment': 'Software Development',
  'ec.organization.serviceProvider.scope.operationsService': 'Operations Service',
  'ec.organization.serviceProvider.scope.hardwareProcurement': 'Hardware Procurement',
  'ec.organization.serviceProvider.scope.integration': 'Integration',
  'ec.organization.serviceProvider.enterpriseNature.centralStateOwned': 'Central State-Owned',
  'ec.organization.serviceProvider.enterpriseNature.stateOwned': 'State-Owned',
  'ec.organization.serviceProvider.enterpriseNature.private': 'Private Enterprise',
  'ec.organization.serviceProvider.enterpriseNature.publicInstitution': 'Public Institution',
  'ec.organization.serviceProvider.vendorLevel.strategicPartner': 'Strategic Partner',
  'ec.organization.serviceProvider.vendorLevel.coreSupplier': 'Core Supplier',
  'ec.organization.serviceProvider.vendorLevel.generalSupplier': 'General Supplier',
  'ec.organization.serviceProvider.relations.hardwareAssets': 'Hardware Assets',
  'ec.organization.serviceProvider.relations.softwareAssets': 'Software Assets',
  'ec.organization.serviceProvider.relations.informationSystems': 'Systems',
  'ec.organization.serviceProvider.relations.persons': 'Persons',
  'ec.organization.serviceProvider.relations.projects': 'Projects',
  'ec.organization.serviceProvider.section.basicInfo': 'Basic Information',
  'ec.organization.serviceProvider.section.relationInfo': 'Relation Information',
  'ec.organization.serviceProvider.page.createTitle': 'Create Service Provider',
  'ec.organization.serviceProvider.page.createDescription': 'Create a service provider using the final delivery fields.',
  'ec.organization.serviceProvider.page.editTitle': 'Edit Service Provider',
  'ec.organization.serviceProvider.page.editDescription': 'Maintain provider profile, level, and business information.',
  'ec.organization.serviceProvider.page.detailTitle': 'Service Provider Detail',
  'ec.organization.serviceProvider.page.detailDescription': 'Review provider master data, business tags, and related resources.',
  'ec.organization.serviceProvider.page.relationsTitle': 'Provider Relations',
  'ec.organization.serviceProvider.page.relationsDescription': 'Maintain relations between the provider and hardware, systems, persons, and projects.',
  'ec.organization.serviceProvider.figma.create': 'Provider Onboarding',
  'ec.organization.serviceProvider.figma.statsLoadFailed': 'Failed to load provider statistics',
  'ec.organization.serviceProvider.figma.type.development': 'Development',
  'ec.organization.serviceProvider.figma.type.ops': 'Operations',
  'ec.organization.serviceProvider.figma.type.hardware': 'Hardware',
  'ec.organization.serviceProvider.figma.type.integration': 'Integration',
  'ec.organization.serviceProvider.figma.stats.total': 'Total Providers',
  'ec.organization.serviceProvider.figma.stats.development': 'Development Providers',
  'ec.organization.serviceProvider.figma.stats.ops': 'Operations Providers',
  'ec.organization.serviceProvider.figma.stats.hardware': 'Hardware Providers',
  'ec.organization.serviceProvider.figma.stats.integration': 'Integration Providers',
  'ec.organization.serviceProvider.upload.success': 'Logo uploaded successfully',
  'ec.organization.serviceProvider.upload.invalidType': 'Only png, jpg, jpeg, webp, and svg images are supported',
  'ec.organization.serviceProvider.upload.sizeExceeded': 'Image size must be 2MB or less',
  'ec.organization.serviceProvider.message.supportLoadFailed': 'Failed to load service provider relation options',

  'ec.organization.person.form.keyword': 'Keyword',
  'ec.organization.person.form.keywordPlaceholder': 'Search by name, employee no. or mobile',
  'ec.organization.person.form.department': 'Department',
  'ec.organization.person.form.departmentPlaceholder': 'Select department',
  'ec.organization.person.form.serviceProvider': 'Service Provider',
  'ec.organization.person.form.serviceProviderPlaceholder': 'Select service provider',
  'ec.organization.person.form.relatedServiceProviders': 'Related Service Providers',
  'ec.organization.person.form.relatedServiceProvidersPlaceholder': 'Select related service providers',
  'ec.organization.person.form.personType': 'Person Type',
  'ec.organization.person.form.personTypePlaceholder': 'Select person type',
  'ec.organization.person.form.status': 'Status',
  'ec.organization.person.form.statusPlaceholder': 'Select person status',
  'ec.organization.person.form.namePlaceholder': 'Enter name',
  'ec.organization.person.form.genderPlaceholder': 'Select gender',
  'ec.organization.person.form.idCardNoPlaceholder': 'Enter ID card no.',
  'ec.organization.person.form.mobilePlaceholder': 'Enter mobile',
  'ec.organization.person.form.employeeNoPlaceholder': 'Enter employee no.',
  'ec.organization.person.form.photoUrlPlaceholder': 'Enter photo URL',
  'ec.organization.person.form.photoPreview': 'Photo Preview',
  'ec.organization.person.form.accountPlaceholder': 'Enter account',
  'ec.organization.person.form.hasOpsAccount': 'Enable Operations Account',
  'ec.organization.person.form.hasOpsAccountDetail': 'Operations Account Enabled',
  'ec.organization.person.form.genderMale': 'Male',
  'ec.organization.person.form.genderFemale': 'Female',
  'ec.organization.person.table.gender': 'Gender',
  'ec.organization.person.table.idCardNo': 'ID Card No.',
  'ec.organization.person.table.mobile': 'Mobile',
  'ec.organization.person.table.employeeNo': 'Employee No.',
  'ec.organization.person.table.photoUrl': 'Photo URL',
  'ec.organization.person.table.account': 'Account',
  'ec.organization.person.table.departmentName': 'Department',
  'ec.organization.person.table.serviceProviderName': 'Service Provider',
  'ec.organization.person.dialog.createTitle': 'Create Person',
  'ec.organization.person.dialog.editTitle': 'Edit Person',
  'ec.organization.person.dialog.relationsTitle': 'Manage Person Relations',
  'ec.organization.person.drawer.title': 'Person Detail',
  'ec.organization.person.validation.nameRequired': 'Please enter the name',
  'ec.organization.person.validation.genderRequired': 'Please select the gender',
  'ec.organization.person.validation.idCardNoRequired': 'Please enter the ID card no.',
  'ec.organization.person.validation.mobileRequired': 'Please enter the mobile',
  'ec.organization.person.validation.serviceProviderRequired': 'Please select the service provider',
  'ec.organization.person.validation.personTypeRequired': 'Please select the person type',
  'ec.organization.person.validation.statusRequired': 'Please select the person status',
  'ec.organization.person.message.loadFailed': 'Failed to load persons',
  'ec.organization.person.message.detailFailed': 'Failed to load person detail',
  'ec.organization.person.message.departmentLoadFailed': 'Failed to load department options',
  'ec.organization.person.relation.saveSuccess': 'Person relations saved successfully',
  'ec.organization.person.relation.saveFailed': 'Failed to save person relations',
  'ec.organization.person.relation.hardwareAssetsPlaceholder': 'Select hardware assets',
  'ec.organization.person.relation.informationSystemsPlaceholder': 'Select systems',
  'ec.organization.person.relation.projectsPlaceholder': 'Select projects',
  'ec.organization.person.relation.relatedServiceProvidersPlaceholder': 'Select related service providers',
  'ec.organization.person.relations.hardwareAssets': 'Hardware Assets',
  'ec.organization.person.relations.informationSystems': 'Systems',
  'ec.organization.person.relations.softwareAssets': 'Software Assets',
  'ec.organization.person.relations.projects': 'Projects',
  'ec.organization.person.relations.relatedServiceProviders': 'Related Service Providers',
  'ec.organization.person.section.basicInfo': 'Basic Information',
  'ec.organization.person.section.relationInfo': 'Relation Information',
  'ec.organization.person.page.createTitle': 'Create Person',
  'ec.organization.person.page.createDescription': 'Create a person profile based on the final Figma delivery design.',
  'ec.organization.person.page.editTitle': 'Edit Person',
  'ec.organization.person.page.editDescription': 'Maintain person basics, operations-account status, and related resources.',
  'ec.organization.person.page.detailTitle': 'Person Detail',
  'ec.organization.person.page.detailDescription': 'Review person basics together with software, hardware, and project relations.',
  'ec.organization.person.page.relationsTitle': 'Person Relations',
  'ec.organization.person.page.relationsDescription': 'Maintain person relations for systems, hardware, service providers, and projects.',
  'ec.organization.person.figma.statsLoadFailed': 'Failed to load person statistics',
  'ec.organization.person.figma.table.company': 'Service Provider / Department',
  'ec.organization.person.figma.table.type': 'Type',
  'ec.organization.person.figma.type.dev': 'Development',
  'ec.organization.person.figma.type.ops': 'Operations',
  'ec.organization.person.figma.stats.total': 'Total Persons',
  'ec.organization.person.figma.stats.development': 'Developers',
  'ec.organization.person.figma.stats.ops': 'Operations Staff',
  'ec.organization.person.figma.stats.hardwareOwners': 'Hardware Owners',
  'ec.organization.person.boolean.yes': 'Yes',
  'ec.organization.person.boolean.no': 'No',
  'ec.organization.person.detail.card.code': 'Code',
  'ec.organization.person.detail.card.type': 'Type',
  'ec.organization.person.detail.card.vendor': 'Vendor',
  'ec.organization.person.detail.card.owner': 'Owner',
  'ec.organization.person.detail.card.ip': 'IP',
  'ec.organization.person.detail.card.cpu': 'CPU',
  'ec.organization.person.detail.card.memory': 'Memory',
  'ec.organization.person.detail.card.status': 'Status',
}
