export default {
  'ec.menu.name.hardware': '硬件资源',
  'ec.menu.name.hardwareAssets': '硬件台账',

  'ec.hardware.common.code': '资产编码',
  'ec.hardware.common.name': '资产名称',
  'ec.hardware.common.category': '硬件分类',
  'ec.hardware.common.status': '硬件状态',
  'ec.hardware.common.department': '所属部门',
  'ec.hardware.common.location': '资产位置',
  'ec.hardware.common.managementIp': '管理 IP',
  'ec.hardware.common.businessIp': '业务 IP',
  'ec.hardware.common.cpuModel': 'CPU 型号',
  'ec.hardware.common.cpuCores': 'CPU 核心数',
  'ec.hardware.common.memoryGb': '内存(GB)',
  'ec.hardware.common.enabledDate': '启用日期',
  'ec.hardware.common.remark': '备注',
  'ec.hardware.common.updatedAt': '更新时间',
  'ec.hardware.common.createdAt': '创建时间',
  'ec.hardware.common.actions': '操作',
  'ec.hardware.common.search': '关键字',
  'ec.hardware.common.searchPlaceholder': '请输入资产编码或名称',
  'ec.hardware.common.create': '新增硬件',
  'ec.hardware.common.edit': '编辑',
  'ec.hardware.common.detail': '详情',
  'ec.hardware.common.delete': '删除',
  'ec.hardware.common.more': '更多',
  'ec.hardware.common.empty': '暂无硬件数据',
  'ec.hardware.common.noData': '暂无数据',
  'ec.hardware.common.yes': '是',
  'ec.hardware.common.no': '否',
  'ec.hardware.common.saveSuccess': '硬件保存成功',
  'ec.hardware.common.saveFailed': '硬件保存失败',
  'ec.hardware.common.deleteSuccess': '硬件删除成功',
  'ec.hardware.common.deleteFailed': '硬件删除失败',
  'ec.hardware.common.deleteConfirm': '确定删除“{name}”吗？',

  'ec.hardware.category.server': '服务器',
  'ec.hardware.category.queryTerminal': '查询机',
  'ec.hardware.category.ticketTerminal': '取号机',
  'ec.hardware.category.selfServiceTerminal': '自助终端',

  'ec.hardware.status.registered': '已登记',
  'ec.hardware.status.inStock': '已入库',
  'ec.hardware.status.assigned': '已分配',
  'ec.hardware.status.changed': '已变更',
  'ec.hardware.status.idle': '闲置',
  'ec.hardware.status.maintaining': '维护中',
  'ec.hardware.status.offline': '已下线',
  'ec.hardware.status.scrapped': '已报废',

  'ec.hardware.action.systems': '关联系统',
  'ec.hardware.action.owners': '负责人',
  'ec.hardware.action.vendors': '服务商',
  'ec.hardware.action.lifecycle': '生命周期',
  'ec.hardware.action.import': '批量导入',
  'ec.hardware.action.export': '导出 CSV',

  'ec.hardware.form.categoryPlaceholder': '请选择硬件分类',
  'ec.hardware.form.statusPlaceholder': '请选择硬件状态',
  'ec.hardware.form.departmentPlaceholder': '请选择部门',
  'ec.hardware.form.locationPlaceholder': '请选择位置',
  'ec.hardware.form.codePlaceholder': '请输入资产编码',
  'ec.hardware.form.namePlaceholder': '请输入资产名称',
  'ec.hardware.form.managementIpPlaceholder': '请输入管理 IP',
  'ec.hardware.form.businessIpPlaceholder': '请输入业务 IP',
  'ec.hardware.form.cpuModelPlaceholder': '请输入 CPU 型号',
  'ec.hardware.form.cpuCoresPlaceholder': '请输入 CPU 核心数',
  'ec.hardware.form.memoryGbPlaceholder': '请输入内存容量',
  'ec.hardware.form.enabledDatePlaceholder': '请选择启用日期',
  'ec.hardware.form.remarkPlaceholder': '请输入备注',
  'ec.hardware.form.os': '操作系统',
  'ec.hardware.form.osPlaceholder': '请输入操作系统',
  'ec.hardware.form.diskGb': '磁盘(GB)',
  'ec.hardware.form.diskGbPlaceholder': '请输入磁盘容量',
  'ec.hardware.form.virtualization': '虚拟化方式',
  'ec.hardware.form.virtualizationPlaceholder': '请输入虚拟化方式',
  'ec.hardware.form.screenSize': '屏幕尺寸',
  'ec.hardware.form.screenSizePlaceholder': '请输入屏幕尺寸',
  'ec.hardware.form.touchEnabled': '支持触摸',
  'ec.hardware.form.deviceModel': '设备型号',
  'ec.hardware.form.deviceModelPlaceholder': '请输入设备型号',
  'ec.hardware.form.printerModel': '打印机型号',
  'ec.hardware.form.printerModelPlaceholder': '请输入打印机型号',
  'ec.hardware.form.supportQr': '支持二维码',
  'ec.hardware.form.terminalType': '终端类型',
  'ec.hardware.form.terminalTypePlaceholder': '请输入终端类型',
  'ec.hardware.form.subtype': '分类扩展信息',
  'ec.hardware.form.basic': '基础信息',
  'ec.hardware.form.createTitle': '新增硬件资产',
  'ec.hardware.form.editTitle': '编辑硬件资产',
  'ec.hardware.form.validation.codeRequired': '请输入资产编码',
  'ec.hardware.form.validation.nameRequired': '请输入资产名称',
  'ec.hardware.form.validation.categoryRequired': '请选择硬件分类',

  'ec.hardware.detail.title': '硬件资产详情',
  'ec.hardware.detail.basic': '基础信息',
  'ec.hardware.detail.subtype': '扩展信息',
  'ec.hardware.detail.systems': '关联系统',
  'ec.hardware.detail.owners': '负责人',
  'ec.hardware.detail.vendors': '服务商',
  'ec.hardware.detail.lifecycle': '生命周期记录',
  'ec.hardware.detail.noneSubtype': '当前分类无扩展信息',
  'ec.hardware.detail.operator': '操作人',
  'ec.hardware.detail.reason': '原因',
  'ec.hardware.detail.actionTime': '操作时间',

  'ec.hardware.relation.systemsTitle': '同步关联系统',
  'ec.hardware.relation.ownersTitle': '同步负责人',
  'ec.hardware.relation.vendorsTitle': '同步服务商',
  'ec.hardware.relation.systemsPlaceholder': '请选择信息系统',
  'ec.hardware.relation.ownersPlaceholder': '请选择负责人',
  'ec.hardware.relation.vendorsPlaceholder': '请选择服务商',
  'ec.hardware.relation.saveSuccess': '关系同步成功',
  'ec.hardware.relation.saveFailed': '关系同步失败',

  'ec.hardware.lifecycle.title': '执行生命周期动作',
  'ec.hardware.lifecycle.action': '生命周期动作',
  'ec.hardware.lifecycle.actionPlaceholder': '请选择动作',
  'ec.hardware.lifecycle.reason': '原因说明',
  'ec.hardware.lifecycle.reasonPlaceholder': '请输入原因说明',
  'ec.hardware.lifecycle.operator': '操作人',
  'ec.hardware.lifecycle.operatorPlaceholder': '请输入操作人',
  'ec.hardware.lifecycle.saveSuccess': '生命周期更新成功',
  'ec.hardware.lifecycle.saveFailed': '生命周期更新失败',
  'ec.hardware.lifecycle.validation.actionRequired': '请选择生命周期动作',
  'ec.hardware.lifecycle.action.register': '登记',
  'ec.hardware.lifecycle.action.inStock': '入库',
  'ec.hardware.lifecycle.action.assign': '分配',
  'ec.hardware.lifecycle.action.change': '变更',
  'ec.hardware.lifecycle.action.idle': '闲置',
  'ec.hardware.lifecycle.action.maintain': '维护',
  'ec.hardware.lifecycle.action.offline': '下线',
  'ec.hardware.lifecycle.action.scrap': '报废',

  'ec.hardware.import.title': '批量导入硬件',
  'ec.hardware.import.payload': '导入 JSON',
  'ec.hardware.import.payloadPlaceholder': '请输入数组，或 {"items":[...]}',
  'ec.hardware.import.helper': '当前后端导入接口接收 JSON，不是文件上传。',
  'ec.hardware.import.example': '示例',
  'ec.hardware.import.submit': '开始导入',
  'ec.hardware.import.success': '批量导入成功',
  'ec.hardware.import.failed': '批量导入失败',

  'ec.hardware.export.success': '导出成功',
  'ec.hardware.export.failed': '导出失败',
  'ec.hardware.load.failed': '硬件列表加载失败',
  'ec.hardware.support.failed': '支撑选项加载失败',
  'ec.hardware.detail.failed': '硬件详情加载失败',
  'ec.hardware.message.statsFailed': '硬件统计加载失败',

  'ec.hardware.common.assetCode': '硬件编码',
  'ec.hardware.common.assetName': '硬件名称',
  'ec.hardware.common.hardwareIp': '硬件IP',
  'ec.hardware.common.hardwareModel': '硬件型号',
  'ec.hardware.common.hardwareBrand': '硬件品牌',
  'ec.hardware.common.hardwareType': '硬件类型',
  'ec.hardware.common.physicalLocation': '物理位置',
  'ec.hardware.common.networkEnvironment': '网络环境',
  'ec.hardware.common.operatingSystem': '操作系统',
  'ec.hardware.common.purchaseDate': '采购时间',
  'ec.hardware.common.owner': '设备负责人',
  'ec.hardware.common.contactPhone': '联系电话',
  'ec.hardware.common.relations': '关联维护',
  'ec.hardware.common.noRelation': '暂无关联数据',

  'ec.hardware.stats.total': '硬件总数',
  'ec.hardware.stats.server': '服务器',
  'ec.hardware.stats.networkDevice': '网络设备',
  'ec.hardware.stats.terminalDevice': '终端设备',
  'ec.hardware.stats.peripheral': '外设',

  'ec.hardware.type.server': '服务器',
  'ec.hardware.type.networkDevice': '网络设备',
  'ec.hardware.type.terminalDevice': '终端设备',
  'ec.hardware.type.peripheral': '外设',

  'ec.hardware.status.running': '正常运行',
  'ec.hardware.status.maintenance': '故障维修',
  'ec.hardware.status.idle': '闲置停用',
  'ec.hardware.status.scrapped': '已报废',

  'ec.hardware.networkEnvironment.extranet': '外网',
  'ec.hardware.networkEnvironment.intranet': '内网',
  'ec.hardware.networkEnvironment.extranetIntranet': '外网/内网',

  'ec.hardware.page.createTitle': '新增硬件',
  'ec.hardware.page.createDescription': '在新版正式入口中维护硬件台账基础信息与关联关系',
  'ec.hardware.page.editTitle': '编辑硬件',
  'ec.hardware.page.editDescription': '更新硬件基础信息、负责人和关联对象',
  'ec.hardware.page.detailTitle': '硬件详情',
  'ec.hardware.page.detailDescription': '查看硬件基础信息以及关联人员、软件、项目',
  'ec.hardware.page.relationsTitle': '关联维护',
  'ec.hardware.page.relationsDescription': '独立维护硬件关联人员、服务商、软件和项目',

  'ec.hardware.section.basic': '基本信息',
  'ec.hardware.section.relations': '关联信息',

  'ec.hardware.form.assetCodePlaceholder': '请输入硬件编码',
  'ec.hardware.form.assetNamePlaceholder': '请输入硬件名称',
  'ec.hardware.form.hardwareIpPlaceholder': '请输入硬件IP',
  'ec.hardware.form.hardwareModelPlaceholder': '请输入硬件型号',
  'ec.hardware.form.hardwareBrandPlaceholder': '请输入硬件品牌',
  'ec.hardware.form.hardwareTypePlaceholder': '请选择硬件类型',
  'ec.hardware.form.physicalLocationPlaceholder': '请输入物理位置',
  'ec.hardware.form.networkEnvironmentPlaceholder': '请选择网络环境',
  'ec.hardware.form.operatingSystemPlaceholder': '请输入操作系统',
  'ec.hardware.form.purchaseDatePlaceholder': '请选择采购时间',
  'ec.hardware.form.ownerPlaceholder': '请输入设备负责人姓名',
  'ec.hardware.form.ownerSelectTitle': '填写设备负责人',
  'ec.hardware.form.contactPhonePlaceholder': '请输入联系电话',

  'ec.hardware.validation.assetCodeRequired': '请输入硬件编码',
  'ec.hardware.validation.assetNameRequired': '请输入硬件名称',
  'ec.hardware.validation.hardwareIpRequired': '请输入硬件IP',
  'ec.hardware.validation.hardwareModelRequired': '请输入硬件型号',
  'ec.hardware.validation.hardwareBrandRequired': '请输入硬件品牌',
  'ec.hardware.validation.hardwareTypeRequired': '请选择硬件类型',
  'ec.hardware.validation.physicalLocationRequired': '请输入物理位置',
  'ec.hardware.validation.networkEnvironmentRequired': '请选择网络环境',
  'ec.hardware.validation.operatingSystemRequired': '请输入操作系统',
  'ec.hardware.validation.purchaseDateRequired': '请选择采购时间',
  'ec.hardware.validation.ownerRequired': '请输入设备负责人姓名',
  'ec.hardware.validation.contactPhoneRequired': '请输入联系电话',
  'ec.hardware.validation.statusRequired': '请选择当前状态',

  'ec.hardware.detail.persons': '关联人员',
  'ec.hardware.detail.softwareAssets': '关联软件',
  'ec.hardware.detail.projects': '关联项目',
  'ec.hardware.detail.serviceProviders': '关联服务商',

  'ec.hardware.relation.personsPlaceholder': '请选择关联人员',
  'ec.hardware.relation.softwareAssetsPlaceholder': '请选择关联软件',
  'ec.hardware.relation.projectsPlaceholder': '请选择关联项目',
  'ec.hardware.relation.serviceProvidersPlaceholder': '请选择关联服务商',

  'ec.hardware.card.employeeNo': '工号',
  'ec.hardware.card.mobile': '电话',
  'ec.hardware.card.softwareType': '软件类型',
  'ec.hardware.card.serviceProviderName': '开发商',
  'ec.hardware.card.ownerName': '负责人',
  'ec.hardware.card.projectType': '项目类型',
  'ec.hardware.card.projectStatus': '项目状态',
  'ec.hardware.card.creditCode': '统一社会信用代码',
  'ec.hardware.card.contact': '商务联系人',
  'ec.hardware.card.phone': '商务电话',
}
