export default {
  'ec.menu.name.software': 'Software',
  'ec.menu.name.softwareAssets': 'Software Assets',

  'ec.software.common.code': 'System Code',
  'ec.software.common.name': 'System Name',
  'ec.software.common.systemType': 'System Type',
  'ec.software.common.status': 'Status',
  'ec.software.common.remark': 'Remark',
  'ec.software.common.createdAt': 'Created At',
  'ec.software.common.updatedAt': 'Updated At',
  'ec.software.common.actions': 'Actions',
  'ec.software.common.search': 'Keyword',
  'ec.software.common.searchPlaceholder': 'Search by system code or name',
  'ec.software.common.create': 'Create Software',
  'ec.software.common.edit': 'Edit',
  'ec.software.common.detail': 'Detail',
  'ec.software.common.relations': 'Relations',
  'ec.software.common.delete': 'Delete',
  'ec.software.common.empty': 'No software data',
  'ec.software.common.noData': 'No data',
  'ec.software.common.saveSuccess': 'Software saved successfully',
  'ec.software.common.saveFailed': 'Failed to save software',
  'ec.software.common.deleteSuccess': 'Software deleted successfully',
  'ec.software.common.deleteFailed': 'Failed to delete software',
  'ec.software.common.deleteConfirm': 'Are you sure you want to delete "{name}"?',

  'ec.software.type.externalService': 'External Service',
  'ec.software.type.internalOffice': 'Internal Office',
  'ec.software.type.supportSystem': 'Support System',

  'ec.software.form.codePlaceholder': 'Enter system code',
  'ec.software.form.namePlaceholder': 'Enter system name',
  'ec.software.form.systemTypePlaceholder': 'Select system type',
  'ec.software.form.statusPlaceholder': 'Select system status',
  'ec.software.form.remarkPlaceholder': 'Enter remark',
  'ec.software.form.createTitle': 'Create Software',
  'ec.software.form.editTitle': 'Edit Software',

  'ec.software.validation.codeRequired': 'Please enter the system code',
  'ec.software.validation.nameRequired': 'Please enter the system name',
  'ec.software.validation.systemTypeRequired': 'Please select the system type',
  'ec.software.validation.statusRequired': 'Please select the system status',

  'ec.software.detail.title': 'Software Detail',
  'ec.software.detail.basic': 'Basic Information',
  'ec.software.detail.serviceProviders': 'Service Providers',
  'ec.software.detail.persons': 'Persons',
  'ec.software.detail.projects': 'Projects',

  'ec.software.relation.title': 'Sync Software Relations',
  'ec.software.relation.serviceProvidersPlaceholder': 'Select service providers',
  'ec.software.relation.personsPlaceholder': 'Select persons',
  'ec.software.relation.projectsPlaceholder': 'Select projects',
  'ec.software.relation.saveSuccess': 'Software relations synced successfully',
  'ec.software.relation.saveFailed': 'Failed to sync software relations',

  'ec.software.message.loadFailed': 'Failed to load software',
  'ec.software.message.detailFailed': 'Failed to load software detail',
  'ec.software.message.supportLoadFailed': 'Failed to load software support options',
}
