export default {
  'ec.menu.name.software': 'Software',
  'ec.menu.name.softwareAssets': 'Software Assets',

  'ec.software.common.code': 'Software Code',
  'ec.software.common.name': 'Software Name',
  'ec.software.common.systemType': 'Software Type',
  'ec.software.common.versionNo': 'Version',
  'ec.software.common.deploymentArchitecture': 'Deployment Architecture',
  'ec.software.common.owner': 'Owner',
  'ec.software.common.contactPhone': 'Contact Phone',
  'ec.software.common.status': 'Status',
  'ec.software.common.remark': 'Remark',
  'ec.software.common.createdAt': 'Created At',
  'ec.software.common.updatedAt': 'Updated At',
  'ec.software.common.actions': 'Actions',
  'ec.software.common.search': 'Keyword',
  'ec.software.common.searchPlaceholder': 'Search by software code or name',
  'ec.software.common.create': 'Create Software',
  'ec.software.common.edit': 'Edit',
  'ec.software.common.detail': 'Detail',
  'ec.software.common.relations': 'Relations',
  'ec.software.common.delete': 'Delete',
  'ec.software.common.empty': 'No software data',
  'ec.software.common.noData': 'No data',
  'ec.software.common.noRelation': 'No related data',
  'ec.software.common.saveSuccess': 'Software saved successfully',
  'ec.software.common.saveFailed': 'Failed to save software',
  'ec.software.common.deleteSuccess': 'Software deleted successfully',
  'ec.software.common.deleteFailed': 'Failed to delete software',
  'ec.software.common.deleteConfirm': 'Are you sure you want to delete "{name}"?',

  'ec.software.section.basic': 'Basic Information',
  'ec.software.section.relations': 'Related Information',

  'ec.software.page.createTitle': 'Create Software',
  'ec.software.page.createDescription': 'Create software in the new final entry and maintain related people, service providers, and hardware together.',
  'ec.software.page.editTitle': 'Edit Software',
  'ec.software.page.editDescription': 'Update software basics and linked objects while keeping the new final entry experience consistent.',
  'ec.software.page.detailTitle': 'Software Detail',
  'ec.software.page.detailDescription': 'Review software basics together with related people, service providers, hardware, and projects.',
  'ec.software.page.relationsTitle': 'Software Relations',
  'ec.software.page.relationsDescription': 'Maintain the related people, service providers, and hardware for this software.',

  'ec.software.type.externalService': 'External Service',
  'ec.software.type.internalOffice': 'Internal Office',
  'ec.software.type.databaseSoftware': 'Database Software',
  'ec.software.type.basicSupport': 'Basic Support',
  'ec.software.type.securitySoftware': 'Security Software',
  'ec.software.type.supportSystem': 'Support System',

  'ec.software.deployment.single': 'Single',
  'ec.software.deployment.cluster': 'Cluster',
  'ec.software.deployment.containerized': 'Containerized',

  'ec.software.stats.total': 'Total Software',
  'ec.software.stats.externalService': 'External Service',
  'ec.software.stats.internalOffice': 'Internal Office',
  'ec.software.stats.databaseSoftware': 'Database Software',
  'ec.software.stats.basicSupport': 'Basic Support',
  'ec.software.stats.securitySoftware': 'Security Software',

  'ec.software.form.codePlaceholder': 'Enter software code',
  'ec.software.form.namePlaceholder': 'Enter software name',
  'ec.software.form.systemTypePlaceholder': 'Select software type',
  'ec.software.form.versionNoPlaceholder': 'Enter version',
  'ec.software.form.deploymentArchitecturePlaceholder': 'Select deployment architecture',
  'ec.software.form.ownerPlaceholder': 'Select owner',
  'ec.software.form.ownerSelectTitle': 'Select Owner',
  'ec.software.form.contactPhonePlaceholder': 'Enter contact phone',
  'ec.software.form.statusPlaceholder': 'Select software status',
  'ec.software.form.remarkPlaceholder': 'Enter remark',
  'ec.software.form.createTitle': 'Create Software',
  'ec.software.form.editTitle': 'Edit Software',

  'ec.software.validation.codeRequired': 'Please enter the software code',
  'ec.software.validation.nameRequired': 'Please enter the software name',
  'ec.software.validation.systemTypeRequired': 'Please select the software type',
  'ec.software.validation.deploymentArchitectureRequired': 'Please select the deployment architecture',
  'ec.software.validation.statusRequired': 'Please select the software status',

  'ec.software.detail.title': 'Software Detail',
  'ec.software.detail.basic': 'Basic Information',
  'ec.software.detail.serviceProviders': 'Service Providers',
  'ec.software.detail.persons': 'People',
  'ec.software.detail.hardwareAssets': 'Hardware Assets',
  'ec.software.detail.projects': 'Projects',

  'ec.software.card.creditCode': 'Unified Credit Code',
  'ec.software.card.contact': 'Business Contact',
  'ec.software.card.phone': 'Phone',
  'ec.software.card.employeeNo': 'Employee No.',
  'ec.software.card.mobile': 'Mobile',
  'ec.software.card.assetCode': 'Asset Code',
  'ec.software.card.managementIp': 'Management IP',
  'ec.software.card.cpuModel': 'CPU Model',
  'ec.software.card.memoryGb': 'Memory (GB)',
  'ec.software.card.projectType': 'Project Type',
  'ec.software.card.projectStatus': 'Project Status',
  'ec.software.card.ownerName': 'Owner',
  'ec.software.card.approvalBatchNo': 'Approval Batch No.',

  'ec.software.relation.title': 'Sync Software Relations',
  'ec.software.relation.serviceProvidersPlaceholder': 'Select service providers',
  'ec.software.relation.personsPlaceholder': 'Select people',
  'ec.software.relation.projectsPlaceholder': 'Select projects',
  'ec.software.relation.hardwareAssetsPlaceholder': 'Select hardware',
  'ec.software.relation.saveSuccess': 'Software relations synced successfully',
  'ec.software.relation.saveFailed': 'Failed to sync software relations',
  'ec.software.relation.partialSaveSuccess': 'Software basics were saved, but relation sync failed. Please review the relations page.',

  'ec.software.message.loadFailed': 'Failed to load software',
  'ec.software.message.detailFailed': 'Failed to load software detail',
  'ec.software.message.supportLoadFailed': 'Failed to load software support options',
  'ec.software.message.statsFailed': 'Failed to load software stats',
}
