export default {
  'ec.menu.name.middleware': 'Middleware',
  'ec.menu.name.middlewareResources': 'Middleware Assets',

  'ec.middleware.common.code': 'Middleware Code',
  'ec.middleware.common.name': 'Middleware Name',
  'ec.middleware.common.type': 'Middleware Type',
  'ec.middleware.common.version': 'Version',
  'ec.middleware.common.status': 'Status',
  'ec.middleware.common.remark': 'Remark',
  'ec.middleware.common.createdAt': 'Created At',
  'ec.middleware.common.updatedAt': 'Updated At',
  'ec.middleware.common.actions': 'Actions',
  'ec.middleware.common.create': 'Create Middleware',
  'ec.middleware.common.edit': 'Edit',
  'ec.middleware.common.detail': 'Detail',
  'ec.middleware.common.delete': 'Delete',
  'ec.middleware.common.empty': 'No middleware data',
  'ec.middleware.common.searchPlaceholder': 'Search by middleware code or name',
  'ec.middleware.common.deleteConfirm': 'Are you sure you want to delete "{name}"?',
  'ec.middleware.common.saveSuccess': 'Middleware saved successfully',
  'ec.middleware.common.saveFailed': 'Failed to save middleware',
  'ec.middleware.common.deleteSuccess': 'Middleware deleted successfully',
  'ec.middleware.common.deleteFailed': 'Failed to delete middleware',

  'ec.middleware.page.createTitle': 'Create Middleware',
  'ec.middleware.page.editTitle': 'Edit Middleware',
  'ec.middleware.page.detailTitle': 'Middleware Detail',
  'ec.middleware.page.description': 'Maintain middleware assets that software can depend on.',
  'ec.middleware.section.basic': 'Basic Information',

  'ec.middleware.form.codePlaceholder': 'Enter middleware code',
  'ec.middleware.form.namePlaceholder': 'Enter middleware name',
  'ec.middleware.form.typePlaceholder': 'Select middleware type',
  'ec.middleware.form.versionPlaceholder': 'Enter version',
  'ec.middleware.form.statusPlaceholder': 'Select status',
  'ec.middleware.form.remarkPlaceholder': 'Enter remark',

  'ec.middleware.validation.codeRequired': 'Please enter the middleware code',
  'ec.middleware.validation.nameRequired': 'Please enter the middleware name',
  'ec.middleware.validation.typeRequired': 'Please select the middleware type',
  'ec.middleware.validation.statusRequired': 'Please select the status',

  'ec.middleware.type.tomcat': 'Tomcat',
  'ec.middleware.type.nginx': 'Nginx',
  'ec.middleware.type.redis': 'Redis',
  'ec.middleware.type.kafka': 'Kafka',
  'ec.middleware.type.rocketmq': 'RocketMQ',
  'ec.middleware.type.elasticsearch': 'Elasticsearch',
  'ec.middleware.type.nacos': 'Nacos',
  'ec.middleware.type.other': 'Other',

  'ec.middleware.status.active': 'Active',
  'ec.middleware.status.inactive': 'Inactive',
  'ec.middleware.stats.total': 'Total Middleware',
  'ec.middleware.stats.active': 'Active',
  'ec.middleware.stats.inactive': 'Inactive',

  'ec.middleware.message.loadFailed': 'Failed to load middleware',
  'ec.middleware.message.detailFailed': 'Failed to load middleware detail',
  'ec.middleware.message.statsFailed': 'Failed to load middleware stats',
}
