export default {
  'ec.menu.name.database': '数据库资源',
  'ec.menu.name.databaseResources': '数据库台账',

  'ec.database.common.code': '数据库编码',
  'ec.database.common.name': '数据库名称',
  'ec.database.common.type': '数据库类型',
  'ec.database.common.version': '版本号',
  'ec.database.common.status': '状态',
  'ec.database.common.remark': '备注',
  'ec.database.common.actions': '操作',
  'ec.database.common.create': '新增数据库',
  'ec.database.common.edit': '编辑',
  'ec.database.common.detail': '详情',
  'ec.database.common.delete': '删除',
  'ec.database.common.empty': '暂无数据库数据',
  'ec.database.common.searchPlaceholder': '请输入数据库编码或名称',
  'ec.database.common.deleteConfirm': '确定删除“{name}”吗？',
  'ec.database.common.saveSuccess': '数据库保存成功',
  'ec.database.common.saveFailed': '数据库保存失败',
  'ec.database.common.deleteSuccess': '数据库删除成功',
  'ec.database.common.deleteFailed': '数据库删除失败',

  'ec.database.page.createTitle': '新增数据库',
  'ec.database.page.editTitle': '编辑数据库',
  'ec.database.page.detailTitle': '数据库详情',
  'ec.database.page.description': '维护软件资源可依赖的数据库基础台账。',
  'ec.database.section.basic': '基础信息',

  'ec.database.form.codePlaceholder': '请输入数据库编码',
  'ec.database.form.namePlaceholder': '请输入数据库名称',
  'ec.database.form.typePlaceholder': '请选择数据库类型',
  'ec.database.form.versionPlaceholder': '请输入版本号',
  'ec.database.form.statusPlaceholder': '请选择状态',
  'ec.database.form.remarkPlaceholder': '请输入备注',

  'ec.database.validation.codeRequired': '请输入数据库编码',
  'ec.database.validation.nameRequired': '请输入数据库名称',
  'ec.database.validation.typeRequired': '请选择数据库类型',
  'ec.database.validation.statusRequired': '请选择状态',

  'ec.database.type.mysql': 'MySQL',
  'ec.database.type.oracle': 'Oracle',
  'ec.database.type.postgresql': 'PostgreSQL',
  'ec.database.type.sqlserver': 'SQL Server',
  'ec.database.type.gaussdb': 'GaussDB',
  'ec.database.type.dameng': '达梦',
  'ec.database.type.other': '其他',

  'ec.database.status.active': '正常',
  'ec.database.status.inactive': '停用',
  'ec.database.stats.total': '数据库总数',
  'ec.database.stats.active': '正常',
  'ec.database.stats.inactive': '停用',

  'ec.database.message.loadFailed': '数据库列表加载失败',
  'ec.database.message.detailFailed': '数据库详情加载失败',
  'ec.database.message.statsFailed': '数据库统计加载失败',
}
