const organizationRoutes = {
  path: '/organization',
  name: 'organization',
  meta: {
    title: '组织资产',
    locale: 'ec.menu.name.organization',
    icon: 'ri-team-line',
    type: 'directory',
    order: 17,
  },
  redirect: '/organization/departments',
  children: [
    {
      path: '/organization/departments',
      name: 'organizationDepartments',
      component: () => import('@/views/organization/departments'),
      meta: {
        title: '部门管理',
        locale: 'ec.menu.name.organizationDepartments',
        type: 'menu',
      },
    },
    {
      path: '/organization/locations',
      name: 'organizationLocations',
      component: () => import('@/views/organization/locations'),
      meta: {
        title: '位置管理',
        locale: 'ec.menu.name.organizationLocations',
        type: 'menu',
      },
    },
    {
      path: '/organization/service-providers',
      name: 'organizationServiceProviders',
      component: () => import('@/views/organization/serviceProvidersFigma'),
      meta: {
        title: '服务商管理',
        locale: 'ec.menu.name.organizationServiceProviders',
        fullpage: true,
        type: 'menu',
      },
    },
    {
      path: '/organization/persons',
      name: 'organizationPersons',
      component: () => import('@/views/organization/personsFigma'),
      meta: {
        title: '人员管理',
        locale: 'ec.menu.name.organizationPersons',
        fullpage: true,
        type: 'menu',
      },
    },
    {
      path: '/organization/service-providers/create',
      name: 'organizationServiceProviderCreate',
      component: () => import('@/views/organization/serviceProviderFormPage'),
      meta: {
        title: '服务商入驻',
        locale: 'ec.organization.serviceProvider.page.createTitle',
        fullpage: true,
        hidden: true,
        active: '/organization/service-providers',
        type: 'menu',
      },
    },
    {
      path: '/organization/service-providers/:id/edit',
      name: 'organizationServiceProviderEdit',
      component: () => import('@/views/organization/serviceProviderFormPage'),
      meta: {
        title: '编辑服务商',
        locale: 'ec.organization.serviceProvider.page.editTitle',
        fullpage: true,
        hidden: true,
        active: '/organization/service-providers',
        type: 'menu',
      },
    },
    {
      path: '/organization/service-providers/:id/detail',
      name: 'organizationServiceProviderDetail',
      component: () => import('@/views/organization/serviceProviderDetailPage'),
      meta: {
        title: '服务商详情',
        locale: 'ec.organization.serviceProvider.page.detailTitle',
        fullpage: true,
        hidden: true,
        active: '/organization/service-providers',
        type: 'menu',
      },
    },
    {
      path: '/organization/service-providers/:id/relations',
      name: 'organizationServiceProviderRelations',
      component: () => import('@/views/organization/serviceProviderRelationsPage'),
      meta: {
        title: '服务商关联维护',
        locale: 'ec.organization.serviceProvider.page.relationsTitle',
        fullpage: true,
        hidden: true,
        active: '/organization/service-providers',
        type: 'menu',
      },
    },
    {
      path: '/organization/persons/create',
      name: 'organizationPersonCreate',
      component: () => import('@/views/organization/personFormPage'),
      meta: {
        title: '新增人员',
        locale: 'ec.organization.person.page.createTitle',
        fullpage: true,
        hidden: true,
        active: '/organization/persons',
        type: 'menu',
      },
    },
    {
      path: '/organization/persons/:id/edit',
      name: 'organizationPersonEdit',
      component: () => import('@/views/organization/personFormPage'),
      meta: {
        title: '编辑人员',
        locale: 'ec.organization.person.page.editTitle',
        fullpage: true,
        hidden: true,
        active: '/organization/persons',
        type: 'menu',
      },
    },
    {
      path: '/organization/persons/:id/detail',
      name: 'organizationPersonDetail',
      component: () => import('@/views/organization/personDetailPage'),
      meta: {
        title: '人员详情',
        locale: 'ec.organization.person.page.detailTitle',
        fullpage: true,
        hidden: true,
        active: '/organization/persons',
        type: 'menu',
      },
    },
    {
      path: '/organization/persons/:id/relations',
      name: 'organizationPersonRelations',
      component: () => import('@/views/organization/personRelationsPage'),
      meta: {
        title: '人员关联维护',
        locale: 'ec.organization.person.page.relationsTitle',
        fullpage: true,
        hidden: true,
        active: '/organization/persons',
        type: 'menu',
      },
    },
  ],
}

export default organizationRoutes
