export default {
  'ec.monitor.dashboard.filter.keyword': '筛选',
  'ec.monitor.dashboard.filter.keyword.placeholder': '请输入主机名、操作系统或节点标识',
  'ec.monitor.dashboard.filter.activeAgent': '当前节点',
  'ec.monitor.dashboard.summary.total': '总服务器数',
  'ec.monitor.dashboard.summary.online': '在线',
  'ec.monitor.dashboard.summary.offline': '离线',
  'ec.monitor.dashboard.summary.abnormal': '异常进程',
  'ec.monitor.dashboard.empty': '没有找到符合条件的服务器',
  'ec.monitor.dashboard.banner.title': '当前活动告警',
  'ec.monitor.dashboard.banner.ackAll': '全部确认',
  'ec.monitor.dashboard.banner.ackOne': '确认',
  'ec.monitor.dashboard.card.online': '在线',
  'ec.monitor.dashboard.card.offline': '离线',
  'ec.monitor.dashboard.card.cpu': '处理器',
  'ec.monitor.dashboard.card.memory': '内存',
  'ec.monitor.dashboard.card.disk': '磁盘',
  'ec.monitor.dashboard.card.alerts': '告警',
  'ec.monitor.dashboard.card.logs': '日志',
  'ec.monitor.dashboard.detail.title': '节点详情',
  'ec.monitor.dashboard.detail.summary': '基础摘要',
  'ec.monitor.dashboard.detail.hardware': '硬件规格',
  'ec.monitor.dashboard.detail.agentId': '节点 ID',
  'ec.monitor.dashboard.detail.host': '主机名',
  'ec.monitor.dashboard.detail.status': '状态',
  'ec.monitor.dashboard.detail.online': '在线',
  'ec.monitor.dashboard.detail.offline': '离线',
  'ec.monitor.dashboard.detail.os': '操作系统',
  'ec.monitor.dashboard.detail.cpu': '处理器',
  'ec.monitor.dashboard.detail.memory': '内存',
  'ec.monitor.dashboard.detail.osArchitecture': '系统架构',
  'ec.monitor.dashboard.detail.cpuCores': '逻辑核数',
  'ec.monitor.dashboard.detail.cpuModel': '处理器型号',
  'ec.monitor.dashboard.detail.memoryUsage': '内存使用',
  'ec.monitor.dashboard.detail.memorySpec': '内存规格',
  'ec.monitor.dashboard.detail.mainBoard': '主板型号',
  'ec.monitor.dashboard.detail.diskOverview': '磁盘总览',
  'ec.monitor.dashboard.detail.gpu': '显卡',
  'ec.monitor.dashboard.detail.processCount': '进程总数',
  'ec.monitor.dashboard.detail.feedbackTime': '最后上报',
  'ec.monitor.dashboard.detail.available': '可用',
  'ec.monitor.dashboard.detail.partitions': '个分区',
  'ec.monitor.dashboard.detail.disks': '磁盘分区',
  'ec.monitor.dashboard.detail.processes': '重点进程',
  'ec.monitor.dashboard.detail.recentLogs': '最近日志',
  'ec.monitor.dashboard.detail.noLogs': '暂无实时日志',
  'ec.monitor.dashboard.detail.actions': '快捷操作',
  'ec.monitor.dashboard.detail.rules': '告警规则',
  'ec.monitor.dashboard.detail.viewAlerts': '查看告警',
  'ec.monitor.dashboard.detail.viewLogs': '查看日志',
  'ec.monitor.dashboard.detail.logMonitors': '日志监听管理',
  'ec.monitor.dashboard.detail.filterRules': '日志过滤规则',
  'ec.monitor.dashboard.detail.ttyd': 'TTYD 管理',
  'ec.monitor.dashboard.detail.noProcesses': '暂无进程信息',
  'ec.monitor.dashboard.process.running': '正常',
  'ec.monitor.dashboard.process.stopped': '异常',
  'ec.monitor.dashboard.alerts.title': '系统告警 - {agentId}',
  'ec.monitor.dashboard.alerts.empty': '暂无未处理告警',
  'ec.monitor.dashboard.alerts.level.critical': '严重',
  'ec.monitor.dashboard.alerts.level.warning': '警告',
  'ec.monitor.dashboard.logs.title': '命中日志 - {agentId}',
  'ec.monitor.dashboard.logs.empty': '暂无命中日志记录',
  'ec.monitor.dashboard.rules.title': '告警规则 - {agentId}',
  'ec.monitor.dashboard.rules.empty': '未配置任何规则',
  'ec.monitor.dashboard.rules.create': '创建新规则',
  'ec.monitor.dashboard.rules.ruleName': '规则名称',
  'ec.monitor.dashboard.rules.ruleName.placeholder': '例如：高 CPU 且低内存',
  'ec.monitor.dashboard.rules.alertLevel': '告警级别',
  'ec.monitor.dashboard.rules.cooldownSec': '冷却时间(秒)',
  'ec.monitor.dashboard.rules.topLogic': '组间逻辑',
  'ec.monitor.dashboard.rules.groupLogic': '组内逻辑',
  'ec.monitor.dashboard.rules.addGroup': '添加条件组',
  'ec.monitor.dashboard.rules.addCondition': '添加条件',
  'ec.monitor.dashboard.rules.delete': '删除',
  'ec.monitor.dashboard.rules.save': '保存规则',
  'ec.monitor.dashboard.rules.cancel': '取消',
  'ec.monitor.dashboard.rules.enabled': '已启用',
  'ec.monitor.dashboard.rules.disabled': '已禁用',
  'ec.monitor.dashboard.rules.global': '全局',
  'ec.monitor.dashboard.rules.conditions': '条件表达式',
  'ec.monitor.dashboard.rules.duration': '持续/窗口(秒)',
  'ec.monitor.dashboard.rules.target': '目标对象',
  'ec.monitor.dashboard.rules.partition': '分区',
  'ec.monitor.dashboard.rules.metric.cpu': 'CPU使用率(%)',
  'ec.monitor.dashboard.rules.metric.memory': '内存使用率(%)',
  'ec.monitor.dashboard.rules.metric.disk': '总磁盘使用率(%)',
  'ec.monitor.dashboard.rules.metric.partition': '分区可用空间(MB)',
  'ec.monitor.dashboard.rules.metric.process': '进程异常',
  'ec.monitor.dashboard.rules.metric.offline': '节点离线',
  'ec.monitor.dashboard.rules.metric.logCritical': 'CRITICAL命中数',
  'ec.monitor.dashboard.rules.metric.logTotal': '日志命中总数',
  'ec.monitor.dashboard.rules.operator.gt': '大于',
  'ec.monitor.dashboard.rules.operator.gte': '大于等于',
  'ec.monitor.dashboard.rules.operator.lt': '小于',
  'ec.monitor.dashboard.rules.operator.lte': '小于等于',
  'ec.monitor.dashboard.rules.operator.eq': '等于',
  'ec.monitor.dashboard.rules.message.loadFailed': '规则加载失败',
  'ec.monitor.dashboard.rules.message.detailFailed': '节点详情加载失败',
  'ec.monitor.dashboard.rules.message.ruleNameRequired': '请输入规则名称',
  'ec.monitor.dashboard.rules.message.groupRequired': '至少需要添加一个判断条件',
  'ec.monitor.dashboard.rules.message.createSuccess': '规则创建成功',
  'ec.monitor.dashboard.rules.message.createFailed': '规则创建失败',
  'ec.monitor.dashboard.rules.message.deleteSuccess': '规则删除成功',
  'ec.monitor.dashboard.rules.message.deleteConfirm': '确定删除当前规则吗？',
  'ec.monitor.dashboard.rules.message.cooldownWarning': '冷却时间小于 Agent 上报间隔(60s)，实际精度会受上报间隔限制，是否继续？',
  'ec.monitor.dashboard.rules.message.durationWarning': '存在持续/窗口时间小于 Agent 上报间隔(60s) 的条件，实际精度会受上报间隔限制，是否继续？',
  'ec.monitor.dashboard.rules.message.helper': '检测频率取决于 Agent 上报间隔，建议持续时间和冷却时间不低于 60 秒。',
  'ec.monitor.dashboard.logMonitor.title': '日志监听管理 - {agentId}',
  'ec.monitor.dashboard.logMonitor.running': '运行中',
  'ec.monitor.dashboard.logMonitor.stopped': '已停止',
  'ec.monitor.dashboard.logMonitor.fileCount': '{count} 个文件',
  'ec.monitor.dashboard.logMonitor.empty': '当前节点暂无日志监听路径',
  'ec.monitor.dashboard.logMonitor.appName': '应用名称',
  'ec.monitor.dashboard.logMonitor.appNamePlaceholder': '例如：受理系统',
  'ec.monitor.dashboard.logMonitor.path': '监听路径',
  'ec.monitor.dashboard.logMonitor.pathPlaceholder': '例如：D:\\logs\\*.log',
  'ec.monitor.dashboard.logMonitor.cancel': '取消',
  'ec.monitor.dashboard.logMonitor.create': '添加监听',
  'ec.monitor.dashboard.logMonitor.delete': '移除',
  'ec.monitor.dashboard.logMonitor.unknownApp': '未知应用',
  'ec.monitor.dashboard.logMonitor.message.loadFailed': '日志监听列表加载失败',
  'ec.monitor.dashboard.logMonitor.message.pathRequired': '监听路径不能为空',
  'ec.monitor.dashboard.logMonitor.message.createSuccess': '日志监听添加成功',
  'ec.monitor.dashboard.logMonitor.message.createFailed': '日志监听添加失败',
  'ec.monitor.dashboard.logMonitor.message.deleteSuccess': '日志监听移除成功',
  'ec.monitor.dashboard.logMonitor.message.deleteFailed': '日志监听移除失败',
  'ec.monitor.dashboard.filterRule.title': '日志过滤规则 - {agentId}',
  'ec.monitor.dashboard.filterRule.global': '全局规则',
  'ec.monitor.dashboard.filterRule.empty': '当前节点暂无专属过滤规则',
  'ec.monitor.dashboard.filterRule.ruleName': '规则名称',
  'ec.monitor.dashboard.filterRule.ruleNamePlaceholder': '例如：排除心跳日志',
  'ec.monitor.dashboard.filterRule.ruleType': '规则类型',
  'ec.monitor.dashboard.filterRule.ruleTypeCritical': '升级为严重告警',
  'ec.monitor.dashboard.filterRule.ruleTypeExclude': '直接忽略',
  'ec.monitor.dashboard.filterRule.ruleTypeBasic': '普通记录',
  'ec.monitor.dashboard.filterRule.matchMode': '匹配模式',
  'ec.monitor.dashboard.filterRule.matchContains': '包含',
  'ec.monitor.dashboard.filterRule.matchEquals': '全等',
  'ec.monitor.dashboard.filterRule.matchRegex': '正则',
  'ec.monitor.dashboard.filterRule.matchStartsWith': '前缀',
  'ec.monitor.dashboard.filterRule.matchEndsWith': '后缀',
  'ec.monitor.dashboard.filterRule.keyword': '关键字 / 表达式',
  'ec.monitor.dashboard.filterRule.keywordPlaceholder': '请输入匹配文本',
  'ec.monitor.dashboard.filterRule.cancel': '取消',
  'ec.monitor.dashboard.filterRule.create': '提交规则',
  'ec.monitor.dashboard.filterRule.delete': '删除',
  'ec.monitor.dashboard.filterRule.message.loadFailed': '日志过滤规则加载失败',
  'ec.monitor.dashboard.filterRule.message.formRequired': '规则名称和关键字不能为空',
  'ec.monitor.dashboard.filterRule.message.createSuccess': '日志过滤规则创建成功',
  'ec.monitor.dashboard.filterRule.message.createFailed': '日志过滤规则创建失败',
  'ec.monitor.dashboard.filterRule.message.deleteSuccess': '日志过滤规则删除成功',
  'ec.monitor.dashboard.filterRule.message.deleteFailed': '日志过滤规则删除失败',
  'ec.monitor.dashboard.ttyd.title': 'TTYD 管理 - {agentId}',
  'ec.monitor.dashboard.ttyd.running': '运行中',
  'ec.monitor.dashboard.ttyd.stopped': '已停止',
  'ec.monitor.dashboard.ttyd.empty': '当前没有运行中的 TTYD 服务',
  'ec.monitor.dashboard.ttyd.portLabel': '端口 {port}',
  'ec.monitor.dashboard.ttyd.serviceMeta': '可写: {writable} | 工作目录: {workingDirectory}',
  'ec.monitor.dashboard.ttyd.open': '打开',
  'ec.monitor.dashboard.ttyd.stop': '停止',
  'ec.monitor.dashboard.ttyd.port': '端口',
  'ec.monitor.dashboard.ttyd.writable': '允许终端写入',
  'ec.monitor.dashboard.ttyd.username': '账号',
  'ec.monitor.dashboard.ttyd.password': '密码',
  'ec.monitor.dashboard.ttyd.cancel': '取消',
  'ec.monitor.dashboard.ttyd.start': '启动并打开',
  'ec.monitor.dashboard.ttyd.message.loadFailed': 'TTYD 服务列表加载失败',
  'ec.monitor.dashboard.ttyd.message.invalidPort': '端口必须是 1-65535 之间的整数',
  'ec.monitor.dashboard.ttyd.message.usernameRequired': '账号不能为空',
  'ec.monitor.dashboard.ttyd.message.passwordRequired': '密码不能为空',
  'ec.monitor.dashboard.ttyd.message.linkMissing': 'TTYD 已启动，但未返回可访问地址',
  'ec.monitor.dashboard.ttyd.message.startSuccess': 'TTYD 已启动',
  'ec.monitor.dashboard.ttyd.message.startFailed': 'TTYD 启动失败',
  'ec.monitor.dashboard.ttyd.message.stopConfirm': '确定停止端口 {port} 的 TTYD 服务吗？',
  'ec.monitor.dashboard.ttyd.message.stopSuccess': 'TTYD 已停止',
  'ec.monitor.dashboard.ttyd.message.stopFailed': 'TTYD 停止失败',
  'ec.monitor.logs.form.agentId': '服务器',
  'ec.monitor.logs.form.agentId.placeholder': '请输入服务器标识',
  'ec.monitor.logs.form.level': '告警级别',
  'ec.monitor.logs.form.level.placeholder': '请选择告警级别',
  'ec.monitor.logs.form.keyword': '关键字',
  'ec.monitor.logs.form.keyword.placeholder': '请输入日志内容、规则名或应用名',
  'ec.monitor.logs.button.refresh': '刷新',
  'ec.monitor.logs.summary.critical': '严重告警',
  'ec.monitor.logs.summary.unknownError': '常规匹配',
  'ec.monitor.logs.summary.total': '当前结果',
  'ec.monitor.logs.table.time': '时间',
  'ec.monitor.logs.table.agentId': '服务器',
  'ec.monitor.logs.table.appName': '应用',
  'ec.monitor.logs.table.level': '级别',
  'ec.monitor.logs.table.rule': '命中规则',
  'ec.monitor.logs.table.content': '日志摘要',
  'ec.monitor.logs.detail.title': '日志审计详情',
  'ec.monitor.logs.detail.agentId': '节点 ID',
  'ec.monitor.logs.detail.appName': '应用名称',
  'ec.monitor.logs.detail.logPath': '日志路径',
  'ec.monitor.logs.detail.rule': '命中规则',
  'ec.monitor.logs.detail.content': '原始日志内容',
  'ec.monitor.logs.level.all': '全部',
  'ec.monitor.logs.level.critical': '严重告警',
  'ec.monitor.logs.level.unknownError': '常规匹配',
  'ec.monitor.logs.empty': '没有符合条件的日志记录',
  'ec.monitor.logs.message.loadFailed': '日志数据加载失败',
  'ec.monitor.logs.message.detailFailed': '日志详情加载失败',
}
