export default {
  'ec.menu.name.middleware': '中间件资源',
  'ec.menu.name.middlewareResources': '中间件台账',

  'ec.middleware.common.code': '中间件编码',
  'ec.middleware.common.name': '中间件名称',
  'ec.middleware.common.type': '中间件类型',
  'ec.middleware.common.version': '版本号',
  'ec.middleware.common.status': '状态',
  'ec.middleware.common.remark': '备注',
  'ec.middleware.common.createdAt': '创建时间',
  'ec.middleware.common.updatedAt': '更新时间',
  'ec.middleware.common.actions': '操作',
  'ec.middleware.common.create': '新增中间件',
  'ec.middleware.common.edit': '编辑',
  'ec.middleware.common.detail': '详情',
  'ec.middleware.common.delete': '删除',
  'ec.middleware.common.empty': '暂无中间件数据',
  'ec.middleware.common.searchPlaceholder': '请输入中间件编码或名称',
  'ec.middleware.common.deleteConfirm': '确定删除“{name}”吗？',
  'ec.middleware.common.saveSuccess': '中间件保存成功',
  'ec.middleware.common.saveFailed': '中间件保存失败',
  'ec.middleware.common.deleteSuccess': '中间件删除成功',
  'ec.middleware.common.deleteFailed': '中间件删除失败',

  'ec.middleware.page.createTitle': '新增中间件',
  'ec.middleware.page.editTitle': '编辑中间件',
  'ec.middleware.page.detailTitle': '中间件详情',
  'ec.middleware.page.description': '维护软件资源可依赖的中间件基础台账。',
  'ec.middleware.section.basic': '基础信息',

  'ec.middleware.form.codePlaceholder': '请输入中间件编码',
  'ec.middleware.form.namePlaceholder': '请输入中间件名称',
  'ec.middleware.form.typePlaceholder': '请选择中间件类型',
  'ec.middleware.form.versionPlaceholder': '请输入版本号',
  'ec.middleware.form.statusPlaceholder': '请选择状态',
  'ec.middleware.form.remarkPlaceholder': '请输入备注',

  'ec.middleware.validation.codeRequired': '请输入中间件编码',
  'ec.middleware.validation.nameRequired': '请输入中间件名称',
  'ec.middleware.validation.typeRequired': '请选择中间件类型',
  'ec.middleware.validation.statusRequired': '请选择状态',

  'ec.middleware.type.tomcat': 'Tomcat',
  'ec.middleware.type.nginx': 'Nginx',
  'ec.middleware.type.redis': 'Redis',
  'ec.middleware.type.kafka': 'Kafka',
  'ec.middleware.type.rocketmq': 'RocketMQ',
  'ec.middleware.type.elasticsearch': 'Elasticsearch',
  'ec.middleware.type.nacos': 'Nacos',
  'ec.middleware.type.other': '其他',

  'ec.middleware.status.active': '正常',
  'ec.middleware.status.inactive': '停用',
  'ec.middleware.stats.total': '中间件总数',
  'ec.middleware.stats.active': '正常',
  'ec.middleware.stats.inactive': '停用',

  'ec.middleware.message.loadFailed': '中间件列表加载失败',
  'ec.middleware.message.detailFailed': '中间件详情加载失败',
  'ec.middleware.message.statsFailed': '中间件统计加载失败',
}
