export default {
  'ec.menu.name.project': 'Projects',
  'ec.menu.name.projectAssets': 'Project Assets',

  'ec.project.common.code': 'Project Code',
  'ec.project.common.name': 'Project Name',
  'ec.project.common.projectType': 'Project Type',
  'ec.project.common.projectStatus': 'Project Status',
  'ec.project.common.approvalBatchNo': 'Approval Batch No.',
  'ec.project.common.projectBudget': 'Budget (10k CNY)',
  'ec.project.common.contractAmount': 'Contract Amount (10k CNY)',
  'ec.project.common.ownerName': 'Owner',
  'ec.project.common.ownerPhone': 'Owner Phone',
  'ec.project.common.approvalDate': 'Approval Date',
  'ec.project.common.startDate': 'Start Date',
  'ec.project.common.initialDeliveryDate': 'Initial Delivery Date',
  'ec.project.common.endDate': 'Final Acceptance Date',
  'ec.project.common.warrantyEndDate': 'Warranty End Date',
  'ec.project.common.stage': 'Current Stage',
  'ec.project.common.paymentCycleName': 'Payment Cycle',
  'ec.project.common.paymentRatio': 'Payment Ratio (%)',
  'ec.project.common.paymentAmount': 'Payment Amount (10k CNY)',
  'ec.project.common.plannedPaymentDate': 'Planned Payment Date',
  'ec.project.common.actualPaymentDate': 'Actual Payment Date',
  'ec.project.common.paymentStatus': 'Payment Status',
  'ec.project.common.remark': 'Remark',
  'ec.project.common.createdAt': 'Created At',
  'ec.project.common.updatedAt': 'Updated At',
  'ec.project.common.actions': 'Actions',
  'ec.project.common.create': 'Create Project',
  'ec.project.common.edit': 'Edit',
  'ec.project.common.detail': 'Detail',
  'ec.project.common.relations': 'Relations',
  'ec.project.common.delete': 'Delete',
  'ec.project.common.empty': 'No project data',
  'ec.project.common.noData': 'No data',
  'ec.project.common.noRelation': 'No relations',
  'ec.project.common.saveSuccess': 'Project saved successfully',
  'ec.project.common.saveFailed': 'Failed to save project',
  'ec.project.common.deleteSuccess': 'Project deleted successfully',
  'ec.project.common.deleteFailed': 'Failed to delete project',
  'ec.project.common.deleteConfirm': 'Delete "{name}"?',

  'ec.project.page.createTitle': 'Create Project',
  'ec.project.page.createDescription': 'Project Assets / Create Project',
  'ec.project.page.editTitle': 'Edit Project',
  'ec.project.page.editDescription': 'Project Assets / Edit Project',
  'ec.project.page.detailTitle': 'Project Detail',
  'ec.project.page.detailDescription': 'Project Assets / Project Detail',
  'ec.project.page.relationsTitle': 'Project Relations',
  'ec.project.page.relationsDescription': 'Project Assets / Project Relations',

  'ec.project.section.basic': 'Basic Information',
  'ec.project.section.owner': 'Project Owner',
  'ec.project.section.period': 'Project Schedule',
  'ec.project.section.payment': 'Payment Cycle',
  'ec.project.section.documents': 'Project Documents',
  'ec.project.section.relations': 'Relations',

  'ec.project.stats.total': 'Total Projects',
  'ec.project.stats.newBuild': 'New Build',
  'ec.project.stats.softwareUpgrade': 'Software Upgrade',
  'ec.project.stats.opsProject': 'Ops Project',
  'ec.project.stats.servicePurchase': 'Service Purchase',
  'ec.project.stats.hardwarePurchase': 'Hardware Purchase',
  'ec.project.stats.integrationProject': 'Integration Project',

  'ec.project.type.newBuild': 'New Build',
  'ec.project.type.softwareUpgrade': 'Software Upgrade',
  'ec.project.type.opsProject': 'Ops Project',
  'ec.project.type.servicePurchase': 'Service Purchase',
  'ec.project.type.hardwarePurchase': 'Hardware Purchase',
  'ec.project.type.integrationProject': 'Integration Project',

  'ec.project.form.keywordPlaceholder': 'Enter project code or name',
  'ec.project.form.codePlaceholder': 'Enter project code',
  'ec.project.form.namePlaceholder': 'Enter project name',
  'ec.project.form.projectTypePlaceholder': 'Select project type',
  'ec.project.form.projectStatusPlaceholder': 'Select project status',
  'ec.project.form.approvalBatchNoPlaceholder': 'Enter approval batch no.',
  'ec.project.form.ownerNamePlaceholder': 'Enter project owner',
  'ec.project.form.ownerPhonePlaceholder': 'Enter owner phone',
  'ec.project.form.stagePlaceholder': 'Enter current stage',
  'ec.project.form.paymentCycleNamePlaceholder': 'Enter payment cycle',
  'ec.project.form.paymentStatusPlaceholder': 'Select payment status',
  'ec.project.form.endDatePlaceholder': 'Select the final acceptance date',

  'ec.project.validation.codeRequired': 'Please enter the project code',
  'ec.project.validation.nameRequired': 'Please enter the project name',
  'ec.project.validation.projectTypeRequired': 'Please select the project type',
  'ec.project.validation.approvalBatchNoRequired': 'Please enter the approval batch no.',
  'ec.project.validation.projectBudgetRequired': 'Please enter the project budget',
  'ec.project.validation.contractAmountRequired': 'Please enter the contract amount',
  'ec.project.validation.ownerNameRequired': 'Please enter the project owner',
  'ec.project.validation.ownerPhoneRequired': 'Please enter the owner phone',
  'ec.project.validation.approvalDateRequired': 'Please select the approval date',
  'ec.project.validation.startDateRequired': 'Please select the start date',
  'ec.project.validation.initialDeliveryDateRequired': 'Please select the initial delivery date',
  'ec.project.validation.endDateRequired': 'Please select the final acceptance date',
  'ec.project.validation.warrantyEndDateRequired': 'Please select the warranty end date',
  'ec.project.validation.stageRequired': 'Please enter the current stage',
  'ec.project.validation.paymentCycleNameRequired': 'Please enter the payment cycle',
  'ec.project.validation.paymentRatioRequired': 'Please enter the payment ratio',
  'ec.project.validation.paymentAmountRequired': 'Please enter the payment amount',
  'ec.project.validation.plannedPaymentDateRequired': 'Please select the planned payment date',
  'ec.project.validation.actualPaymentDateRequired': 'Please select the actual payment date',
  'ec.project.validation.paymentStatusRequired': 'Please select the payment status',

  'ec.project.detail.persons': 'Related Persons',
  'ec.project.detail.informationSystems': 'Related Software',
  'ec.project.detail.hardwareAssets': 'Related Hardware',
  'ec.project.detail.serviceProviders': 'Related Service Providers',

  'ec.project.relation.title': 'Sync Project Relations',
  'ec.project.relation.personsPlaceholder': 'Select persons',
  'ec.project.relation.informationSystemsPlaceholder': 'Select systems',
  'ec.project.relation.hardwareAssetsPlaceholder': 'Select hardware assets',
  'ec.project.relation.serviceProvidersPlaceholder': 'Select service providers',
  'ec.project.relation.saveSuccess': 'Project relations synced successfully',
  'ec.project.relation.saveFailed': 'Failed to sync project relations',

  'ec.project.document.name': 'File Name',
  'ec.project.document.size': 'Size',
  'ec.project.document.uploadedAt': 'Uploaded At',
  'ec.project.document.upload': 'Upload Document',
  'ec.project.document.select': 'Select Files',
  'ec.project.document.cancelUpload': 'Cancel Upload',
  'ec.project.document.confirmUpload': 'Confirm Upload',
  'ec.project.document.view': 'View',
  'ec.project.document.empty': 'No documents',
  'ec.project.document.savedTitle': 'Uploaded Documents',
  'ec.project.document.savedHint': 'Uploaded documents will take effect after the project is saved.',
  'ec.project.document.queueHint': 'Batch upload is supported. Up to 5 files can be added at a time.',
  'ec.project.document.dropTitle': 'Drag files here, or click to upload',
  'ec.project.document.dropHint': 'Supports PNG/JPG/PDF/Word/Excel files, up to 100MB each',
  'ec.project.document.resultSummary': '{total} files uploaded, {success} succeeded, {failed} failed',
  'ec.project.document.queueEmpty': 'No files are queued for upload yet.',
  'ec.project.document.pending': 'Pending',
  'ec.project.document.uploading': 'Uploading',
  'ec.project.document.success': 'Uploaded',
  'ec.project.document.failed': 'Failed',
  'ec.project.document.clearQueueSuccess': 'The upload queue has been cleared',
  'ec.project.document.uploadSuccess': 'Document uploaded successfully',
  'ec.project.document.uploadFailed': 'Failed to upload document',
  'ec.project.document.invalidType': 'Only PNG/JPG/WEBP/PDF/Word/Excel files are allowed',
  'ec.project.document.sizeExceeded': 'The file size cannot exceed 100MB',
  'ec.project.document.uploadLimitExceeded': 'You can queue up to 5 files only',
  'ec.project.document.noPending': 'No files are waiting to be uploaded',
  'ec.project.document.partialSuccess': 'Upload finished with failed files',
  'ec.project.document.allFailed': 'All document uploads failed',
  'ec.project.document.detailHint': 'You can review project documents such as approvals, contracts, technical reports, test files, and audit reports.',
  'ec.project.document.unfinishedQueue': 'Please confirm the upload or clear the remaining queued files first',

  'ec.project.card.code': 'Code',
  'ec.project.card.type': 'Type',
  'ec.project.card.status': 'Status',
  'ec.project.card.vendor': 'Service Provider',
  'ec.project.card.owner': 'Owner',
  'ec.project.card.ip': 'IP',
  'ec.project.card.cpu': 'CPU',
  'ec.project.card.memory': 'Memory',
  'ec.project.card.employeeNo': 'Employee No.',
  'ec.project.card.mobile': 'Mobile',
  'ec.project.card.creditCode': 'Credit Code',
  'ec.project.card.scope': 'Scope',
  'ec.project.card.score': 'Score',
  'ec.project.card.contact': 'Business Contact',
  'ec.project.card.phone': 'Business Phone',

  'ec.project.message.loadFailed': 'Failed to load project list',
  'ec.project.message.detailFailed': 'Failed to load project detail',
  'ec.project.message.supportLoadFailed': 'Failed to load support data',
  'ec.project.message.statsFailed': 'Failed to load project stats',
}
