export default {
  'ec.menu.name.project': 'Project',
  'ec.menu.name.projectAssets': 'Project Assets',

  'ec.project.common.code': 'Project Code',
  'ec.project.common.name': 'Project Name',
  'ec.project.common.projectType': 'Project Type',
  'ec.project.common.projectStatus': 'Project Status',
  'ec.project.common.startDate': 'Start Date',
  'ec.project.common.endDate': 'End Date',
  'ec.project.common.remark': 'Remark',
  'ec.project.common.createdAt': 'Created At',
  'ec.project.common.updatedAt': 'Updated At',
  'ec.project.common.actions': 'Actions',
  'ec.project.common.search': 'Keyword',
  'ec.project.common.searchPlaceholder': 'Search by project code or name',
  'ec.project.common.create': 'Create Project',
  'ec.project.common.edit': 'Edit',
  'ec.project.common.detail': 'Detail',
  'ec.project.common.relations': 'Relations',
  'ec.project.common.delete': 'Delete',
  'ec.project.common.empty': 'No project data',
  'ec.project.common.noData': 'No data',
  'ec.project.common.saveSuccess': 'Project saved successfully',
  'ec.project.common.saveFailed': 'Failed to save project',
  'ec.project.common.deleteSuccess': 'Project deleted successfully',
  'ec.project.common.deleteFailed': 'Failed to delete project',
  'ec.project.common.deleteConfirm': 'Are you sure you want to delete "{name}"?',

  'ec.project.type.newBuild': 'New Build',
  'ec.project.type.operation': 'Operation',
  'ec.project.type.upgrade': 'Upgrade',

  'ec.project.status.planning': 'Planning',
  'ec.project.status.building': 'Building',
  'ec.project.status.delayed': 'Delayed',
  'ec.project.status.operating': 'Operating',
  'ec.project.status.terminated': 'Terminated',
  'ec.project.status.finished': 'Finished',

  'ec.project.form.codePlaceholder': 'Enter project code',
  'ec.project.form.namePlaceholder': 'Enter project name',
  'ec.project.form.projectTypePlaceholder': 'Select project type',
  'ec.project.form.projectStatusPlaceholder': 'Select project status',
  'ec.project.form.startDatePlaceholder': 'Select start date',
  'ec.project.form.endDatePlaceholder': 'Select end date',
  'ec.project.form.remarkPlaceholder': 'Enter remark',
  'ec.project.form.createTitle': 'Create Project',
  'ec.project.form.editTitle': 'Edit Project',

  'ec.project.validation.codeRequired': 'Please enter the project code',
  'ec.project.validation.nameRequired': 'Please enter the project name',
  'ec.project.validation.projectTypeRequired': 'Please select the project type',
  'ec.project.validation.projectStatusRequired': 'Please select the project status',

  'ec.project.detail.title': 'Project Detail',
  'ec.project.detail.basic': 'Basic Information',
  'ec.project.detail.informationSystems': 'Systems',
  'ec.project.detail.serviceProviders': 'Service Providers',
  'ec.project.detail.persons': 'Persons',
  'ec.project.detail.hardwareAssets': 'Hardware Assets',

  'ec.project.relation.title': 'Sync Project Relations',
  'ec.project.relation.informationSystemsPlaceholder': 'Select systems',
  'ec.project.relation.serviceProvidersPlaceholder': 'Select service providers',
  'ec.project.relation.personsPlaceholder': 'Select persons',
  'ec.project.relation.hardwareAssetsPlaceholder': 'Select hardware assets',
  'ec.project.relation.saveSuccess': 'Project relations synced successfully',
  'ec.project.relation.saveFailed': 'Failed to sync project relations',

  'ec.project.message.loadFailed': 'Failed to load projects',
  'ec.project.message.detailFailed': 'Failed to load project detail',
  'ec.project.message.supportLoadFailed': 'Failed to load project support options',
}
