export default {
  'ec.menu.name.database': 'Database',
  'ec.menu.name.databaseResources': 'Database Assets',

  'ec.database.common.code': 'Database Code',
  'ec.database.common.name': 'Database Name',
  'ec.database.common.type': 'Database Type',
  'ec.database.common.version': 'Version',
  'ec.database.common.status': 'Status',
  'ec.database.common.remark': 'Remark',
  'ec.database.common.actions': 'Actions',
  'ec.database.common.create': 'Create Database',
  'ec.database.common.edit': 'Edit',
  'ec.database.common.detail': 'Detail',
  'ec.database.common.delete': 'Delete',
  'ec.database.common.empty': 'No database data',
  'ec.database.common.searchPlaceholder': 'Search by database code or name',
  'ec.database.common.deleteConfirm': 'Are you sure you want to delete "{name}"?',
  'ec.database.common.saveSuccess': 'Database saved successfully',
  'ec.database.common.saveFailed': 'Failed to save database',
  'ec.database.common.deleteSuccess': 'Database deleted successfully',
  'ec.database.common.deleteFailed': 'Failed to delete database',

  'ec.database.page.createTitle': 'Create Database',
  'ec.database.page.editTitle': 'Edit Database',
  'ec.database.page.detailTitle': 'Database Detail',
  'ec.database.page.description': 'Maintain database assets that software can depend on.',
  'ec.database.section.basic': 'Basic Information',

  'ec.database.form.codePlaceholder': 'Enter database code',
  'ec.database.form.namePlaceholder': 'Enter database name',
  'ec.database.form.typePlaceholder': 'Select database type',
  'ec.database.form.versionPlaceholder': 'Enter version',
  'ec.database.form.statusPlaceholder': 'Select status',
  'ec.database.form.remarkPlaceholder': 'Enter remark',

  'ec.database.validation.codeRequired': 'Please enter the database code',
  'ec.database.validation.nameRequired': 'Please enter the database name',
  'ec.database.validation.typeRequired': 'Please select the database type',
  'ec.database.validation.statusRequired': 'Please select the status',

  'ec.database.type.mysql': 'MySQL',
  'ec.database.type.oracle': 'Oracle',
  'ec.database.type.postgresql': 'PostgreSQL',
  'ec.database.type.sqlserver': 'SQL Server',
  'ec.database.type.gaussdb': 'GaussDB',
  'ec.database.type.dameng': 'Dameng',
  'ec.database.type.other': 'Other',

  'ec.database.status.active': 'Active',
  'ec.database.status.inactive': 'Inactive',
  'ec.database.stats.total': 'Total Database',
  'ec.database.stats.active': 'Active',
  'ec.database.stats.inactive': 'Inactive',

  'ec.database.message.loadFailed': 'Failed to load database',
  'ec.database.message.detailFailed': 'Failed to load database detail',
  'ec.database.message.statsFailed': 'Failed to load database stats',
}
