export default {
  'ec.menu.name.hardware': 'Hardware',
  'ec.menu.name.hardwareAssets': 'Hardware Assets',

  'ec.hardware.common.code': 'Asset Code',
  'ec.hardware.common.name': 'Asset Name',
  'ec.hardware.common.category': 'Category',
  'ec.hardware.common.status': 'Status',
  'ec.hardware.common.department': 'Department',
  'ec.hardware.common.location': 'Location',
  'ec.hardware.common.managementIp': 'Management IP',
  'ec.hardware.common.businessIp': 'Business IP',
  'ec.hardware.common.cpuModel': 'CPU Model',
  'ec.hardware.common.cpuCores': 'CPU Cores',
  'ec.hardware.common.memoryGb': 'Memory (GB)',
  'ec.hardware.common.enabledDate': 'Enabled Date',
  'ec.hardware.common.remark': 'Remark',
  'ec.hardware.common.updatedAt': 'Updated At',
  'ec.hardware.common.createdAt': 'Created At',
  'ec.hardware.common.actions': 'Actions',
  'ec.hardware.common.search': 'Keyword',
  'ec.hardware.common.searchPlaceholder': 'Search by asset code or name',
  'ec.hardware.common.create': 'Create Hardware',
  'ec.hardware.common.edit': 'Edit',
  'ec.hardware.common.detail': 'Detail',
  'ec.hardware.common.delete': 'Delete',
  'ec.hardware.common.more': 'More',
  'ec.hardware.common.empty': 'No hardware data',
  'ec.hardware.common.noData': 'No data',
  'ec.hardware.common.yes': 'Yes',
  'ec.hardware.common.no': 'No',
  'ec.hardware.common.saveSuccess': 'Hardware saved successfully',
  'ec.hardware.common.saveFailed': 'Failed to save hardware',
  'ec.hardware.common.deleteSuccess': 'Hardware deleted successfully',
  'ec.hardware.common.deleteFailed': 'Failed to delete hardware',
  'ec.hardware.common.deleteConfirm': 'Are you sure you want to delete "{name}"?',

  'ec.hardware.category.server': 'Server',
  'ec.hardware.category.queryTerminal': 'Query Terminal',
  'ec.hardware.category.ticketTerminal': 'Ticket Terminal',
  'ec.hardware.category.selfServiceTerminal': 'Self-Service Terminal',

  'ec.hardware.status.registered': 'Registered',
  'ec.hardware.status.inStock': 'In Stock',
  'ec.hardware.status.assigned': 'Assigned',
  'ec.hardware.status.changed': 'Changed',
  'ec.hardware.status.idle': 'Idle',
  'ec.hardware.status.maintaining': 'Maintaining',
  'ec.hardware.status.offline': 'Offline',
  'ec.hardware.status.scrapped': 'Scrapped',

  'ec.hardware.action.systems': 'Systems',
  'ec.hardware.action.owners': 'Owners',
  'ec.hardware.action.vendors': 'Vendors',
  'ec.hardware.action.lifecycle': 'Lifecycle',
  'ec.hardware.action.import': 'Batch Import',
  'ec.hardware.action.export': 'Export CSV',

  'ec.hardware.form.categoryPlaceholder': 'Select category',
  'ec.hardware.form.statusPlaceholder': 'Select status',
  'ec.hardware.form.departmentPlaceholder': 'Select department',
  'ec.hardware.form.locationPlaceholder': 'Select location',
  'ec.hardware.form.codePlaceholder': 'Enter asset code',
  'ec.hardware.form.namePlaceholder': 'Enter asset name',
  'ec.hardware.form.managementIpPlaceholder': 'Enter management IP',
  'ec.hardware.form.businessIpPlaceholder': 'Enter business IP',
  'ec.hardware.form.cpuModelPlaceholder': 'Enter CPU model',
  'ec.hardware.form.cpuCoresPlaceholder': 'Enter CPU cores',
  'ec.hardware.form.memoryGbPlaceholder': 'Enter memory size',
  'ec.hardware.form.enabledDatePlaceholder': 'Select enabled date',
  'ec.hardware.form.remarkPlaceholder': 'Enter remark',
  'ec.hardware.form.os': 'Operating System',
  'ec.hardware.form.osPlaceholder': 'Enter operating system',
  'ec.hardware.form.diskGb': 'Disk (GB)',
  'ec.hardware.form.diskGbPlaceholder': 'Enter disk size',
  'ec.hardware.form.virtualization': 'Virtualization',
  'ec.hardware.form.virtualizationPlaceholder': 'Enter virtualization mode',
  'ec.hardware.form.screenSize': 'Screen Size',
  'ec.hardware.form.screenSizePlaceholder': 'Enter screen size',
  'ec.hardware.form.touchEnabled': 'Touch Enabled',
  'ec.hardware.form.deviceModel': 'Device Model',
  'ec.hardware.form.deviceModelPlaceholder': 'Enter device model',
  'ec.hardware.form.printerModel': 'Printer Model',
  'ec.hardware.form.printerModelPlaceholder': 'Enter printer model',
  'ec.hardware.form.supportQr': 'QR Supported',
  'ec.hardware.form.terminalType': 'Terminal Type',
  'ec.hardware.form.terminalTypePlaceholder': 'Enter terminal type',
  'ec.hardware.form.subtype': 'Subtype Details',
  'ec.hardware.form.basic': 'Basic Information',
  'ec.hardware.form.createTitle': 'Create Hardware Asset',
  'ec.hardware.form.editTitle': 'Edit Hardware Asset',
  'ec.hardware.form.validation.codeRequired': 'Please enter the asset code',
  'ec.hardware.form.validation.nameRequired': 'Please enter the asset name',
  'ec.hardware.form.validation.categoryRequired': 'Please select the hardware category',

  'ec.hardware.detail.title': 'Hardware Asset Detail',
  'ec.hardware.detail.basic': 'Basic Information',
  'ec.hardware.detail.subtype': 'Subtype Details',
  'ec.hardware.detail.systems': 'Systems',
  'ec.hardware.detail.owners': 'Owners',
  'ec.hardware.detail.vendors': 'Vendors',
  'ec.hardware.detail.lifecycle': 'Lifecycle Records',
  'ec.hardware.detail.noneSubtype': 'No subtype details',
  'ec.hardware.detail.operator': 'Operator',
  'ec.hardware.detail.reason': 'Reason',
  'ec.hardware.detail.actionTime': 'Action Time',

  'ec.hardware.relation.systemsTitle': 'Sync Systems',
  'ec.hardware.relation.ownersTitle': 'Sync Owner',
  'ec.hardware.relation.vendorsTitle': 'Sync Vendors',
  'ec.hardware.relation.systemsPlaceholder': 'Select systems',
  'ec.hardware.relation.ownersPlaceholder': 'Select owner',
  'ec.hardware.relation.vendorsPlaceholder': 'Select vendors',
  'ec.hardware.relation.saveSuccess': 'Relations synced successfully',
  'ec.hardware.relation.saveFailed': 'Failed to sync relations',

  'ec.hardware.lifecycle.title': 'Execute Lifecycle Action',
  'ec.hardware.lifecycle.action': 'Action',
  'ec.hardware.lifecycle.actionPlaceholder': 'Select action',
  'ec.hardware.lifecycle.reason': 'Reason',
  'ec.hardware.lifecycle.reasonPlaceholder': 'Enter reason',
  'ec.hardware.lifecycle.operator': 'Operator',
  'ec.hardware.lifecycle.operatorPlaceholder': 'Enter operator',
  'ec.hardware.lifecycle.saveSuccess': 'Lifecycle updated successfully',
  'ec.hardware.lifecycle.saveFailed': 'Failed to update lifecycle',
  'ec.hardware.lifecycle.validation.actionRequired': 'Please select a lifecycle action',
  'ec.hardware.lifecycle.action.register': 'Register',
  'ec.hardware.lifecycle.action.inStock': 'In Stock',
  'ec.hardware.lifecycle.action.assign': 'Assign',
  'ec.hardware.lifecycle.action.change': 'Change',
  'ec.hardware.lifecycle.action.idle': 'Idle',
  'ec.hardware.lifecycle.action.maintain': 'Maintain',
  'ec.hardware.lifecycle.action.offline': 'Offline',
  'ec.hardware.lifecycle.action.scrap': 'Scrap',

  'ec.hardware.import.title': 'Batch Import Hardware',
  'ec.hardware.import.payload': 'Import JSON',
  'ec.hardware.import.payloadPlaceholder': 'Enter an array, or {"items":[...]}',
  'ec.hardware.import.helper': 'The current backend import API accepts JSON, not file upload.',
  'ec.hardware.import.example': 'Example',
  'ec.hardware.import.submit': 'Import',
  'ec.hardware.import.success': 'Batch import succeeded',
  'ec.hardware.import.failed': 'Batch import failed',

  'ec.hardware.export.success': 'Export succeeded',
  'ec.hardware.export.failed': 'Export failed',
  'ec.hardware.load.failed': 'Failed to load hardware assets',
  'ec.hardware.support.failed': 'Failed to load support options',
  'ec.hardware.detail.failed': 'Failed to load hardware detail',
}
