export default {
  'ec.menu.name.hardware': 'Hardware',
  'ec.menu.name.hardwareAssets': 'Hardware Assets',

  'ec.hardware.common.code': 'Asset Code',
  'ec.hardware.common.name': 'Asset Name',
  'ec.hardware.common.category': 'Category',
  'ec.hardware.common.status': 'Status',
  'ec.hardware.common.department': 'Department',
  'ec.hardware.common.location': 'Location',
  'ec.hardware.common.managementIp': 'Management IP',
  'ec.hardware.common.businessIp': 'Business IP',
  'ec.hardware.common.cpuModel': 'CPU Model',
  'ec.hardware.common.cpuCores': 'CPU Cores',
  'ec.hardware.common.memoryGb': 'Memory (GB)',
  'ec.hardware.common.enabledDate': 'Enabled Date',
  'ec.hardware.common.remark': 'Remark',
  'ec.hardware.common.updatedAt': 'Updated At',
  'ec.hardware.common.createdAt': 'Created At',
  'ec.hardware.common.actions': 'Actions',
  'ec.hardware.common.search': 'Keyword',
  'ec.hardware.common.searchPlaceholder': 'Search by asset code or name',
  'ec.hardware.common.create': 'Create Hardware',
  'ec.hardware.common.edit': 'Edit',
  'ec.hardware.common.detail': 'Detail',
  'ec.hardware.common.delete': 'Delete',
  'ec.hardware.common.more': 'More',
  'ec.hardware.common.empty': 'No hardware data',
  'ec.hardware.common.noData': 'No data',
  'ec.hardware.common.yes': 'Yes',
  'ec.hardware.common.no': 'No',
  'ec.hardware.common.saveSuccess': 'Hardware saved successfully',
  'ec.hardware.common.saveFailed': 'Failed to save hardware',
  'ec.hardware.common.deleteSuccess': 'Hardware deleted successfully',
  'ec.hardware.common.deleteFailed': 'Failed to delete hardware',
  'ec.hardware.common.deleteConfirm': 'Are you sure you want to delete "{name}"?',

  'ec.hardware.category.server': 'Server',
  'ec.hardware.category.queryTerminal': 'Query Terminal',
  'ec.hardware.category.ticketTerminal': 'Ticket Terminal',
  'ec.hardware.category.selfServiceTerminal': 'Self-Service Terminal',

  'ec.hardware.status.registered': 'Registered',
  'ec.hardware.status.inStock': 'In Stock',
  'ec.hardware.status.assigned': 'Assigned',
  'ec.hardware.status.changed': 'Changed',
  'ec.hardware.status.idle': 'Idle',
  'ec.hardware.status.maintaining': 'Maintaining',
  'ec.hardware.status.offline': 'Offline',
  'ec.hardware.status.scrapped': 'Scrapped',

  'ec.hardware.action.systems': 'Systems',
  'ec.hardware.action.owners': 'Owners',
  'ec.hardware.action.vendors': 'Vendors',
  'ec.hardware.action.lifecycle': 'Lifecycle',
  'ec.hardware.action.import': 'Batch Import',
  'ec.hardware.action.export': 'Export CSV',

  'ec.hardware.form.categoryPlaceholder': 'Select category',
  'ec.hardware.form.statusPlaceholder': 'Select status',
  'ec.hardware.form.departmentPlaceholder': 'Select department',
  'ec.hardware.form.locationPlaceholder': 'Select location',
  'ec.hardware.form.codePlaceholder': 'Enter asset code',
  'ec.hardware.form.namePlaceholder': 'Enter asset name',
  'ec.hardware.form.managementIpPlaceholder': 'Enter management IP',
  'ec.hardware.form.businessIpPlaceholder': 'Enter business IP',
  'ec.hardware.form.cpuModelPlaceholder': 'Enter CPU model',
  'ec.hardware.form.cpuCoresPlaceholder': 'Enter CPU cores',
  'ec.hardware.form.memoryGbPlaceholder': 'Enter memory size',
  'ec.hardware.form.enabledDatePlaceholder': 'Select enabled date',
  'ec.hardware.form.remarkPlaceholder': 'Enter remark',
  'ec.hardware.form.os': 'Operating System',
  'ec.hardware.form.osPlaceholder': 'Enter operating system',
  'ec.hardware.form.diskGb': 'Disk (GB)',
  'ec.hardware.form.diskGbPlaceholder': 'Enter disk size',
  'ec.hardware.form.virtualization': 'Virtualization',
  'ec.hardware.form.virtualizationPlaceholder': 'Enter virtualization mode',
  'ec.hardware.form.screenSize': 'Screen Size',
  'ec.hardware.form.screenSizePlaceholder': 'Enter screen size',
  'ec.hardware.form.touchEnabled': 'Touch Enabled',
  'ec.hardware.form.deviceModel': 'Device Model',
  'ec.hardware.form.deviceModelPlaceholder': 'Enter device model',
  'ec.hardware.form.printerModel': 'Printer Model',
  'ec.hardware.form.printerModelPlaceholder': 'Enter printer model',
  'ec.hardware.form.supportQr': 'QR Supported',
  'ec.hardware.form.terminalType': 'Terminal Type',
  'ec.hardware.form.terminalTypePlaceholder': 'Enter terminal type',
  'ec.hardware.form.subtype': 'Subtype Details',
  'ec.hardware.form.basic': 'Basic Information',
  'ec.hardware.form.createTitle': 'Create Hardware Asset',
  'ec.hardware.form.editTitle': 'Edit Hardware Asset',
  'ec.hardware.form.validation.codeRequired': 'Please enter the asset code',
  'ec.hardware.form.validation.nameRequired': 'Please enter the asset name',
  'ec.hardware.form.validation.categoryRequired': 'Please select the hardware category',

  'ec.hardware.detail.title': 'Hardware Asset Detail',
  'ec.hardware.detail.basic': 'Basic Information',
  'ec.hardware.detail.subtype': 'Subtype Details',
  'ec.hardware.detail.systems': 'Systems',
  'ec.hardware.detail.owners': 'Owners',
  'ec.hardware.detail.vendors': 'Vendors',
  'ec.hardware.detail.lifecycle': 'Lifecycle Records',
  'ec.hardware.detail.noneSubtype': 'No subtype details',
  'ec.hardware.detail.operator': 'Operator',
  'ec.hardware.detail.reason': 'Reason',
  'ec.hardware.detail.actionTime': 'Action Time',

  'ec.hardware.relation.systemsTitle': 'Sync Systems',
  'ec.hardware.relation.ownersTitle': 'Sync Owner',
  'ec.hardware.relation.vendorsTitle': 'Sync Vendors',
  'ec.hardware.relation.systemsPlaceholder': 'Select systems',
  'ec.hardware.relation.ownersPlaceholder': 'Select owner',
  'ec.hardware.relation.vendorsPlaceholder': 'Select vendors',
  'ec.hardware.relation.saveSuccess': 'Relations synced successfully',
  'ec.hardware.relation.saveFailed': 'Failed to sync relations',

  'ec.hardware.lifecycle.title': 'Execute Lifecycle Action',
  'ec.hardware.lifecycle.action': 'Action',
  'ec.hardware.lifecycle.actionPlaceholder': 'Select action',
  'ec.hardware.lifecycle.reason': 'Reason',
  'ec.hardware.lifecycle.reasonPlaceholder': 'Enter reason',
  'ec.hardware.lifecycle.operator': 'Operator',
  'ec.hardware.lifecycle.operatorPlaceholder': 'Enter operator',
  'ec.hardware.lifecycle.saveSuccess': 'Lifecycle updated successfully',
  'ec.hardware.lifecycle.saveFailed': 'Failed to update lifecycle',
  'ec.hardware.lifecycle.validation.actionRequired': 'Please select a lifecycle action',
  'ec.hardware.lifecycle.action.register': 'Register',
  'ec.hardware.lifecycle.action.inStock': 'In Stock',
  'ec.hardware.lifecycle.action.assign': 'Assign',
  'ec.hardware.lifecycle.action.change': 'Change',
  'ec.hardware.lifecycle.action.idle': 'Idle',
  'ec.hardware.lifecycle.action.maintain': 'Maintain',
  'ec.hardware.lifecycle.action.offline': 'Offline',
  'ec.hardware.lifecycle.action.scrap': 'Scrap',

  'ec.hardware.import.title': 'Batch Import Hardware',
  'ec.hardware.import.payload': 'Import JSON',
  'ec.hardware.import.payloadPlaceholder': 'Enter an array, or {"items":[...]}',
  'ec.hardware.import.helper': 'The current backend import API accepts JSON, not file upload.',
  'ec.hardware.import.example': 'Example',
  'ec.hardware.import.submit': 'Import',
  'ec.hardware.import.success': 'Batch import succeeded',
  'ec.hardware.import.failed': 'Batch import failed',

  'ec.hardware.export.success': 'Export succeeded',
  'ec.hardware.export.failed': 'Export failed',
  'ec.hardware.load.failed': 'Failed to load hardware assets',
  'ec.hardware.support.failed': 'Failed to load support options',
  'ec.hardware.detail.failed': 'Failed to load hardware detail',
  'ec.hardware.message.statsFailed': 'Failed to load hardware statistics',

  'ec.hardware.common.assetCode': 'Hardware Code',
  'ec.hardware.common.assetName': 'Hardware Name',
  'ec.hardware.common.hardwareIp': 'Hardware IP',
  'ec.hardware.common.hardwareModel': 'Hardware Model',
  'ec.hardware.common.hardwareBrand': 'Hardware Brand',
  'ec.hardware.common.hardwareType': 'Hardware Type',
  'ec.hardware.common.physicalLocation': 'Physical Location',
  'ec.hardware.common.networkEnvironment': 'Network Environment',
  'ec.hardware.common.operatingSystem': 'Operating System',
  'ec.hardware.common.purchaseDate': 'Purchase Date',
  'ec.hardware.common.owner': 'Device Owner',
  'ec.hardware.common.contactPhone': 'Contact Phone',
  'ec.hardware.common.relations': 'Relations',
  'ec.hardware.common.noRelation': 'No related data',

  'ec.hardware.stats.total': 'Total Hardware',
  'ec.hardware.stats.server': 'Servers',
  'ec.hardware.stats.networkDevice': 'Network Devices',
  'ec.hardware.stats.terminalDevice': 'Terminal Devices',
  'ec.hardware.stats.peripheral': 'Peripherals',

  'ec.hardware.type.server': 'Server',
  'ec.hardware.type.networkDevice': 'Network Device',
  'ec.hardware.type.terminalDevice': 'Terminal Device',
  'ec.hardware.type.peripheral': 'Peripheral',

  'ec.hardware.status.running': 'Running',
  'ec.hardware.status.maintenance': 'Maintenance',
  'ec.hardware.status.idle': 'Idle',
  'ec.hardware.status.scrapped': 'Scrapped',

  'ec.hardware.networkEnvironment.extranet': 'Extranet',
  'ec.hardware.networkEnvironment.intranet': 'Intranet',
  'ec.hardware.networkEnvironment.extranetIntranet': 'Extranet / Intranet',

  'ec.hardware.page.createTitle': 'Create Hardware',
  'ec.hardware.page.createDescription': 'Maintain hardware ledger information and relations in the new official entry.',
  'ec.hardware.page.editTitle': 'Edit Hardware',
  'ec.hardware.page.editDescription': 'Update hardware basics, owner, and related objects.',
  'ec.hardware.page.detailTitle': 'Hardware Detail',
  'ec.hardware.page.detailDescription': 'View hardware basics together with related persons, software, and projects.',
  'ec.hardware.page.relationsTitle': 'Relation Maintenance',
  'ec.hardware.page.relationsDescription': 'Maintain related persons, service providers, software, and projects independently.',

  'ec.hardware.section.basic': 'Basic Information',
  'ec.hardware.section.relations': 'Relation Information',

  'ec.hardware.form.assetCodePlaceholder': 'Enter hardware code',
  'ec.hardware.form.assetNamePlaceholder': 'Enter hardware name',
  'ec.hardware.form.hardwareIpPlaceholder': 'Enter hardware IP',
  'ec.hardware.form.hardwareModelPlaceholder': 'Enter hardware model',
  'ec.hardware.form.hardwareBrandPlaceholder': 'Enter hardware brand',
  'ec.hardware.form.hardwareTypePlaceholder': 'Select hardware type',
  'ec.hardware.form.physicalLocationPlaceholder': 'Enter physical location',
  'ec.hardware.form.networkEnvironmentPlaceholder': 'Select network environment',
  'ec.hardware.form.operatingSystemPlaceholder': 'Enter operating system',
  'ec.hardware.form.purchaseDatePlaceholder': 'Select purchase date',
  'ec.hardware.form.ownerPlaceholder': 'Enter device owner name',
  'ec.hardware.form.ownerSelectTitle': 'Enter Device Owner Name',
  'ec.hardware.form.contactPhonePlaceholder': 'Enter contact phone',

  'ec.hardware.validation.assetCodeRequired': 'Please enter the hardware code',
  'ec.hardware.validation.assetNameRequired': 'Please enter the hardware name',
  'ec.hardware.validation.hardwareIpRequired': 'Please enter the hardware IP',
  'ec.hardware.validation.hardwareModelRequired': 'Please enter the hardware model',
  'ec.hardware.validation.hardwareBrandRequired': 'Please enter the hardware brand',
  'ec.hardware.validation.hardwareTypeRequired': 'Please select the hardware type',
  'ec.hardware.validation.physicalLocationRequired': 'Please enter the physical location',
  'ec.hardware.validation.networkEnvironmentRequired': 'Please select the network environment',
  'ec.hardware.validation.operatingSystemRequired': 'Please enter the operating system',
  'ec.hardware.validation.purchaseDateRequired': 'Please select the purchase date',
  'ec.hardware.validation.ownerRequired': 'Please enter the device owner name',
  'ec.hardware.validation.contactPhoneRequired': 'Please enter the contact phone',
  'ec.hardware.validation.statusRequired': 'Please select the current status',

  'ec.hardware.detail.persons': 'Related Persons',
  'ec.hardware.detail.softwareAssets': 'Related Software',
  'ec.hardware.detail.projects': 'Related Projects',
  'ec.hardware.detail.serviceProviders': 'Related Service Providers',

  'ec.hardware.relation.personsPlaceholder': 'Select related persons',
  'ec.hardware.relation.softwareAssetsPlaceholder': 'Select related software',
  'ec.hardware.relation.projectsPlaceholder': 'Select related projects',
  'ec.hardware.relation.serviceProvidersPlaceholder': 'Select related service providers',

  'ec.hardware.card.employeeNo': 'Employee No.',
  'ec.hardware.card.mobile': 'Phone',
  'ec.hardware.card.softwareType': 'Software Type',
  'ec.hardware.card.serviceProviderName': 'Vendor',
  'ec.hardware.card.ownerName': 'Owner',
  'ec.hardware.card.projectType': 'Project Type',
  'ec.hardware.card.projectStatus': 'Project Status',
  'ec.hardware.card.creditCode': 'Unified Social Credit Code',
  'ec.hardware.card.contact': 'Business Contact',
  'ec.hardware.card.phone': 'Business Phone',
}
