export default {
  'ec.menu.name.project': '项目资源',
  'ec.menu.name.projectAssets': '项目台账',

  'ec.project.common.code': '项目编码',
  'ec.project.common.name': '项目名称',
  'ec.project.common.projectType': '项目类型',
  'ec.project.common.projectStatus': '项目状态',
  'ec.project.common.startDate': '开始日期',
  'ec.project.common.endDate': '结束日期',
  'ec.project.common.remark': '备注',
  'ec.project.common.createdAt': '创建时间',
  'ec.project.common.updatedAt': '更新时间',
  'ec.project.common.actions': '操作',
  'ec.project.common.search': '关键字',
  'ec.project.common.searchPlaceholder': '请输入项目编码或名称',
  'ec.project.common.create': '新增项目',
  'ec.project.common.edit': '编辑',
  'ec.project.common.detail': '详情',
  'ec.project.common.relations': '关联维护',
  'ec.project.common.delete': '删除',
  'ec.project.common.empty': '暂无项目数据',
  'ec.project.common.noData': '暂无数据',
  'ec.project.common.saveSuccess': '项目保存成功',
  'ec.project.common.saveFailed': '项目保存失败',
  'ec.project.common.deleteSuccess': '项目删除成功',
  'ec.project.common.deleteFailed': '项目删除失败',
  'ec.project.common.deleteConfirm': '确定删除“{name}”吗？',

  'ec.project.type.newBuild': '新建',
  'ec.project.type.operation': '运营',
  'ec.project.type.upgrade': '升级',

  'ec.project.status.planning': '规划中',
  'ec.project.status.building': '建设中',
  'ec.project.status.delayed': '延期',
  'ec.project.status.operating': '运行中',
  'ec.project.status.terminated': '终止',
  'ec.project.status.finished': '已完成',

  'ec.project.form.codePlaceholder': '请输入项目编码',
  'ec.project.form.namePlaceholder': '请输入项目名称',
  'ec.project.form.projectTypePlaceholder': '请选择项目类型',
  'ec.project.form.projectStatusPlaceholder': '请选择项目状态',
  'ec.project.form.startDatePlaceholder': '请选择开始日期',
  'ec.project.form.endDatePlaceholder': '请选择结束日期',
  'ec.project.form.remarkPlaceholder': '请输入备注',
  'ec.project.form.createTitle': '新增项目',
  'ec.project.form.editTitle': '编辑项目',

  'ec.project.validation.codeRequired': '请输入项目编码',
  'ec.project.validation.nameRequired': '请输入项目名称',
  'ec.project.validation.projectTypeRequired': '请选择项目类型',
  'ec.project.validation.projectStatusRequired': '请选择项目状态',

  'ec.project.detail.title': '项目详情',
  'ec.project.detail.basic': '基础信息',
  'ec.project.detail.informationSystems': '关联系统',
  'ec.project.detail.serviceProviders': '服务商',
  'ec.project.detail.persons': '负责人',
  'ec.project.detail.hardwareAssets': '关联硬件',

  'ec.project.relation.title': '同步项目关联关系',
  'ec.project.relation.informationSystemsPlaceholder': '请选择信息系统',
  'ec.project.relation.serviceProvidersPlaceholder': '请选择服务商',
  'ec.project.relation.personsPlaceholder': '请选择人员',
  'ec.project.relation.hardwareAssetsPlaceholder': '请选择硬件资产',
  'ec.project.relation.saveSuccess': '项目关系同步成功',
  'ec.project.relation.saveFailed': '项目关系同步失败',

  'ec.project.message.loadFailed': '项目列表加载失败',
  'ec.project.message.detailFailed': '项目详情加载失败',
  'ec.project.message.supportLoadFailed': '项目支撑选项加载失败',
}
