export default {
  'ec.menu.name.project': '项目资源',
  'ec.menu.name.projectAssets': '项目资源',

  'ec.project.common.code': '项目编码',
  'ec.project.common.name': '项目名称',
  'ec.project.common.projectType': '项目类型',
  'ec.project.common.projectStatus': '项目状态',
  'ec.project.common.approvalBatchNo': '立项批号',
  'ec.project.common.projectBudget': '项目预算(万元)',
  'ec.project.common.contractAmount': '项目合同金额(万元)',
  'ec.project.common.ownerName': '项目负责人',
  'ec.project.common.ownerPhone': '负责人电话',
  'ec.project.common.approvalDate': '立项时间',
  'ec.project.common.startDate': '开工时间',
  'ec.project.common.initialDeliveryDate': '初验时间',
  'ec.project.common.endDate': '终验时间',
  'ec.project.common.warrantyEndDate': '质保截止时间',
  'ec.project.common.stage': '当前阶段',
  'ec.project.common.paymentCycleName': '资金支付周期',
  'ec.project.common.paymentRatio': '付款比例(%)',
  'ec.project.common.paymentAmount': '付款金额(万元)',
  'ec.project.common.plannedPaymentDate': '计划付款时间',
  'ec.project.common.actualPaymentDate': '实际付款时间',
  'ec.project.common.paymentStatus': '付款状态',
  'ec.project.common.remark': '备注',
  'ec.project.common.createdAt': '创建时间',
  'ec.project.common.updatedAt': '更新时间',
  'ec.project.common.actions': '操作',
  'ec.project.common.create': '新增项目',
  'ec.project.common.edit': '编辑',
  'ec.project.common.detail': '详情',
  'ec.project.common.relations': '关联维护',
  'ec.project.common.delete': '删除',
  'ec.project.common.empty': '暂无项目数据',
  'ec.project.common.noData': '暂无数据',
  'ec.project.common.noRelation': '暂无关联信息',
  'ec.project.common.saveSuccess': '项目保存成功',
  'ec.project.common.saveFailed': '项目保存失败',
  'ec.project.common.deleteSuccess': '项目删除成功',
  'ec.project.common.deleteFailed': '项目删除失败',
  'ec.project.common.deleteConfirm': '确定删除“{name}”吗？',

  'ec.project.page.createTitle': '新增项目',
  'ec.project.page.createDescription': '项目资源 / 新增项目',
  'ec.project.page.editTitle': '编辑项目',
  'ec.project.page.editDescription': '项目资源 / 编辑项目',
  'ec.project.page.detailTitle': '项目详情',
  'ec.project.page.detailDescription': '项目资源 / 项目详情',
  'ec.project.page.relationsTitle': '项目关联维护',
  'ec.project.page.relationsDescription': '项目资源 / 项目关联维护',

  'ec.project.section.basic': '基本信息',
  'ec.project.section.owner': '项目负责人',
  'ec.project.section.period': '项目周期',
  'ec.project.section.payment': '资金支付周期',
  'ec.project.section.documents': '项目文档',
  'ec.project.section.relations': '关联信息',

  'ec.project.stats.total': '项目总数',
  'ec.project.stats.newBuild': '新建项目',
  'ec.project.stats.softwareUpgrade': '软件升级',
  'ec.project.stats.opsProject': '运维项目',
  'ec.project.stats.servicePurchase': '购买服务',
  'ec.project.stats.hardwarePurchase': '硬件采购',
  'ec.project.stats.integrationProject': '集成项目',

  'ec.project.type.newBuild': '新建项目',
  'ec.project.type.softwareUpgrade': '软件升级',
  'ec.project.type.opsProject': '运维项目',
  'ec.project.type.servicePurchase': '购买服务',
  'ec.project.type.hardwarePurchase': '硬件采购',
  'ec.project.type.integrationProject': '集成项目',

  'ec.project.form.keywordPlaceholder': '请输入项目编码或名称',
  'ec.project.form.contentPlaceholder': '请输入内容',
  'ec.project.form.selectPlaceholder': '请选择',
  'ec.project.form.codePlaceholder': '请输入项目编码',
  'ec.project.form.namePlaceholder': '请输入项目名称',
  'ec.project.form.projectTypePlaceholder': '请选择项目类型',
  'ec.project.form.projectStatusPlaceholder': '请选择项目状态',
  'ec.project.form.approvalBatchNoPlaceholder': '请输入立项批号',
  'ec.project.form.ownerNamePlaceholder': '请输入项目负责人',
  'ec.project.form.ownerPhonePlaceholder': '请输入负责人电话',
  'ec.project.form.stagePlaceholder': '请输入当前阶段',
  'ec.project.form.paymentCycleNamePlaceholder': '请输入资金支付周期',
  'ec.project.form.paymentStatusPlaceholder': '请选择付款状态',
  'ec.project.form.endDatePlaceholder': '请选择终验时间',
  'ec.project.form.projectBudgetLabel': '项目预算',
  'ec.project.form.contractAmountLabel': '项目合同金额',
  'ec.project.form.ownerNameLabel': '姓名',
  'ec.project.form.ownerPhoneLabel': '联系电话',
  'ec.project.form.paymentCycleNameLabel': '周期名称',
  'ec.project.form.paymentRatioLabel': '付款比例',
  'ec.project.form.paymentAmountLabel': '付款金额',
  'ec.project.form.paymentStatusLabel': '状态',

  'ec.project.validation.codeRequired': '请输入项目编码',
  'ec.project.validation.nameRequired': '请输入项目名称',
  'ec.project.validation.projectTypeRequired': '请选择项目类型',
  'ec.project.validation.approvalBatchNoRequired': '请输入立项批号',
  'ec.project.validation.projectBudgetRequired': '请输入项目预算',
  'ec.project.validation.contractAmountRequired': '请输入项目合同金额',
  'ec.project.validation.ownerNameRequired': '请输入项目负责人',
  'ec.project.validation.ownerPhoneRequired': '请输入负责人电话',
  'ec.project.validation.approvalDateRequired': '请选择立项时间',
  'ec.project.validation.startDateRequired': '请选择开工时间',
  'ec.project.validation.initialDeliveryDateRequired': '请选择初验时间',
  'ec.project.validation.endDateRequired': '请选择终验时间',
  'ec.project.validation.warrantyEndDateRequired': '请选择质保截止时间',
  'ec.project.validation.stageRequired': '请输入当前阶段',
  'ec.project.validation.paymentCycleNameRequired': '请输入资金支付周期',
  'ec.project.validation.paymentRatioRequired': '请输入付款比例',
  'ec.project.validation.paymentAmountRequired': '请输入付款金额',
  'ec.project.validation.plannedPaymentDateRequired': '请选择计划付款时间',
  'ec.project.validation.actualPaymentDateRequired': '请选择实际付款时间',
  'ec.project.validation.paymentStatusRequired': '请选择付款状态',

  'ec.project.detail.persons': '关联人员',
  'ec.project.detail.informationSystems': '关联软件',
  'ec.project.detail.hardwareAssets': '关联硬件',
  'ec.project.detail.serviceProviders': '关联服务商',

  'ec.project.relation.title': '同步项目关联关系',
  'ec.project.relation.personsPlaceholder': '请选择关联人员',
  'ec.project.relation.informationSystemsPlaceholder': '请选择关联系统',
  'ec.project.relation.hardwareAssetsPlaceholder': '请选择关联硬件',
  'ec.project.relation.serviceProvidersPlaceholder': '请选择关联服务商',
  'ec.project.relation.saveSuccess': '项目关系同步成功',
  'ec.project.relation.saveFailed': '项目关系同步失败',

  'ec.project.document.name': '文件名',
  'ec.project.document.size': '大小',
  'ec.project.document.uploadedAt': '上传时间',
  'ec.project.document.upload': '上传文档',
  'ec.project.document.select': '点击上传',
  'ec.project.document.cancelUpload': '取消上传',
  'ec.project.document.confirmUpload': '确认上传',
  'ec.project.document.view': '查看',
  'ec.project.document.empty': '暂无项目文档',
  'ec.project.document.savedTitle': '已上传文档',
  'ec.project.document.savedHint': '已上传成功的项目文档会在保存项目后生效。',
  'ec.project.document.queueHint': '支持批量上传文件，文件格式不限，最多只能上传 5 份文件',
  'ec.project.document.dropTitle': '将文件拖到此处上传，或点击上传',
  'ec.project.document.dropHint': '支持png/jpg/pdf/word/excel文件等，不超过100M',
  'ec.project.document.resultSummary': '共上传 {total} 个文件，成功 {success} 个，失败 {failed} 个',
  'ec.project.document.resultSummary.totalPrefix': '共上传 ',
  'ec.project.document.resultSummary.totalSuffix': ' 个文件，',
  'ec.project.document.resultSummary.successPrefix': '成功 ',
  'ec.project.document.resultSummary.successSuffix': ' 个，',
  'ec.project.document.resultSummary.failedPrefix': '失败 ',
  'ec.project.document.resultSummary.failedSuffix': ' 个',
  'ec.project.document.queueEmpty': '暂无待上传文件，请先选择或拖拽文件。',
  'ec.project.document.pending': '待上传',
  'ec.project.document.uploading': '上传中',
  'ec.project.document.success': '上传成功',
  'ec.project.document.failed': '上传失败',
  'ec.project.document.clearQueueSuccess': '待上传队列已清空',
  'ec.project.document.uploadSuccess': '文档上传成功',
  'ec.project.document.uploadFailed': '文档上传失败',
  'ec.project.document.invalidType': '仅支持上传 PNG/JPG/WEBP/PDF/Word/Excel 文件',
  'ec.project.document.sizeExceeded': '单个文档大小不能超过 100MB',
  'ec.project.document.uploadLimitExceeded': '最多只能上传 5 份文件',
  'ec.project.document.noPending': '暂无待上传文件',
  'ec.project.document.partialSuccess': '文档上传完成，存在失败文件',
  'ec.project.document.allFailed': '文档上传失败，请重试',
  'ec.project.document.detailHint': '支持查看立项报告、合同扫描件、技术报告、测评文件、审计报告等项目文档。',
  'ec.project.document.unfinishedQueue': '请先确认上传或取消待上传队列中的文件',

  'ec.project.card.code': '编码',
  'ec.project.card.type': '类型',
  'ec.project.card.status': '状态',
  'ec.project.card.vendor': '服务商',
  'ec.project.card.owner': '负责人',
  'ec.project.card.ip': 'IP地址',
  'ec.project.card.cpu': 'CPU',
  'ec.project.card.memory': '内存',
  'ec.project.card.employeeNo': '工号',
  'ec.project.card.mobile': '手机号',
  'ec.project.card.creditCode': '统一社会信用代码',
  'ec.project.card.scope': '合作范围',
  'ec.project.card.score': '评分',
  'ec.project.card.contact': '商务联系人',
  'ec.project.card.phone': '联系电话',

  'ec.project.message.loadFailed': '项目列表加载失败',
  'ec.project.message.detailFailed': '项目详情加载失败',
  'ec.project.message.supportLoadFailed': '项目支撑数据加载失败',
  'ec.project.message.statsFailed': '项目统计加载失败',
}
